<script setup lang="ts">
import Comparison from '~/components/industrial/Comparison.vue'
import IndustrialHeader from '~/components/industrial/Header.vue'
import IndustrialFooter from '~/components/industrial/Footer.vue'
import ProductCard from '~/components/industrial/ProductCard.vue'
import { productFamilies, industrialProducts } from '~/constants/industrial'
import { campaignWhatsapp } from '~/utils/campaign'
import type { IndustrialProduct } from '~/types/industrial'
definePageMeta({ layout: 'demonstracao' })
useDemoSeo('Atlas Industrial — catálogo técnico', 'Catálogo demonstrativo de válvulas, reguladores e instrumentos com busca, filtros e fichas técnicas.')
const { query, family, selected, filtered, clear } = useIndustrialCatalog()
const quoteDialog = ref<HTMLDialogElement | null>(null)
function quote(product: IndustrialProduct): void { selected.value = product; quoteDialog.value?.showModal() }
</script>
<template>
  <div class="bg-[#f6f8f9] text-[#163b50]"><IndustrialHeader /><div class="mx-auto max-w-[1240px] px-6 pb-16 pt-9"><nav aria-label="Localização" class="mb-8 flex gap-3 text-xs text-slate-500"><NuxtLink to="/exemplos/industrial" class="hover:underline">Atlas Industrial</NuxtLink><span aria-hidden="true">/</span><span>Catálogo</span></nav><div class="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p class="text-[11px] font-semibold uppercase tracking-[0.18em] text-[#418b8b]">Conheça a linha de produtos</p><h1 class="mt-3 font-heading text-4xl font-semibold tracking-tight md:text-5xl">Catálogo técnico.</h1></div><p class="max-w-md text-base leading-7 text-slate-500">Busque um modelo, selecione uma família e consulte suas características. Documentação organizada para a sua avaliação.</p></div>
    <div class="mt-9 grid items-end gap-4 border border-slate-200 bg-white p-5 md:grid-cols-[1fr_240px_auto]"><div><label for="catalog-search" class="mb-2 block text-xs font-semibold">Buscar produto</label><input id="catalog-search" v-model="query" type="search" placeholder="Nome, modelo ou fabricante…" class="h-12 w-full rounded-none border border-slate-300 bg-white px-4 text-sm text-[#163b50]"></div><div><label for="catalog-family" class="mb-2 block text-xs font-semibold">Família de produto</label><select id="catalog-family" v-model="family" class="h-12 w-full border border-slate-300 bg-white px-3 text-sm"><option value="todos">Todas as famílias</option><option v-for="item in productFamilies" :key="item.id" :value="item.id">{{ item.name }}</option></select></div><button class="h-12 border border-slate-300 px-5 text-sm hover:bg-slate-50" @click="clear">Limpar filtros</button></div>
    <p role="status" aria-live="polite" class="my-5 text-xs text-slate-500">{{ filtered.length }} {{ filtered.length === 1 ? 'produto encontrado' : 'produtos encontrados' }} · {{ industrialProducts.length }} referências no catálogo</p><div v-if="filtered.length" class="grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><ProductCard v-for="product in filtered" :key="product.id" :product="product" @quote="quote" /></div><div v-else class="border border-dashed border-slate-300 bg-white px-6 py-20 text-center"><h2 class="font-heading text-2xl font-semibold">Nenhum produto encontrado.</h2><p class="mt-3 text-base text-slate-500">Experimente outro nome, modelo ou família.</p><button class="mt-6 bg-[#163b50] px-5 py-3 text-sm text-white" @click="clear">Ver todos os produtos</button></div>
    <Comparison />
    <p class="mt-8 max-w-3xl text-xs leading-6 text-slate-500">Demonstração sem comercialização de equipamentos. As características variam por configuração; consulte a ficha completa vinculada a cada modelo. As marcas identificam os fabricantes de referência e não representam parceria com a Avyro.</p></div><IndustrialFooter />
    <dialog ref="quoteDialog" aria-labelledby="quote-title" class="w-[min(540px,92vw)] bg-white p-7 text-[#163b50]"><div v-if="selected"><div class="flex items-center justify-between gap-4"><p class="text-[11px] uppercase tracking-widest text-[#418b8b]">Demonstração de cotação</p><button class="border border-slate-200 px-3 py-2 text-xs" autofocus @click="quoteDialog?.close()">Fechar ✕</button></div><h2 id="quote-title" class="mt-7 font-heading text-2xl font-semibold">{{ selected.name }}</h2><p class="mt-2 text-base text-slate-500">{{ selected.manufacturer }} · Modelo {{ selected.model }}</p><p class="mt-6 text-base leading-7 text-slate-500">Em um site da sua empresa, o atendimento receberia o produto selecionado junto ao pedido. Este exemplo não envia uma cotação de equipamento.</p><a :href="campaignWhatsapp(`um site industrial com catálogo e cotação de produtos, como o exemplo ${selected.model}`)" target="_blank" rel="noopener noreferrer" class="mt-7 block bg-[#163b50] px-5 py-4 text-center text-sm font-semibold text-white hover:bg-[#24526a]">Quero um catálogo assim ↗</a><p class="mt-4 text-xs text-slate-400">A conversa será com a Avyro, sobre criação de sites.</p></div></dialog>
  </div>
</template>
