<script setup lang="ts">
import QuoteList from '~/components/industrial/QuoteList.vue'
import IndustrialHeader from '~/components/industrial/Header.vue'
import IndustrialFooter from '~/components/industrial/Footer.vue'
import { productFamilies } from '~/constants/industrial'
import { campaignWhatsapp } from '~/utils/campaign'
definePageMeta({ layout: 'demonstracao' })
useDemoSeo('Atlas Industrial — válvulas e instrumentação', 'Demonstração de site industrial com catálogo técnico de válvulas, reguladores e instrumentos de pressão.')
const applications = [
  { title: 'Criogenia & gases técnicos', text: 'Válvulas e reguladores apresentados com materiais, conexões e limites de operação.', number: '01' },
  { title: 'Máquinas & equipamentos', text: 'Instrumentação de pressão para identificar opções de medição e interfaces de processo.', number: '02' },
  { title: 'Processos industriais', text: 'Documentação técnica organizada para apoiar a avaliação de cada aplicação.', number: '03' },
]
</script>
<template>
  <div class="bg-white text-[#163b50]"><IndustrialHeader />
    <section class="relative overflow-hidden bg-[#0e2634] text-white"><img src="/images/campaign/industrial.jpg" alt="Tubulações e equipamentos de uma instalação industrial" width="1800" height="1100" fetchpriority="high" class="absolute inset-0 h-full w-full object-cover opacity-30"><div class="relative mx-auto grid max-w-[1240px] gap-12 px-6 py-20 md:grid-cols-[1.5fr_0.5fr] md:py-28"><div><p class="text-[11px] font-semibold uppercase tracking-[0.2em] text-[#80d2d2]">Controle de processos · Informação técnica</p><h1 class="mt-6 max-w-3xl font-heading text-[42px] font-semibold leading-[1.12] tracking-[-0.045em] md:text-[64px]">Precisão na escolha.<br>Controle em<br><span class="text-[#80d2d2]">cada processo.</span></h1><p class="mt-7 max-w-xl text-base leading-8 text-slate-300">Válvulas, reguladores e instrumentação. Encontre famílias de produtos, compare características e consulte a documentação técnica.</p><div class="mt-9 flex flex-wrap gap-4"><NuxtLink to="/exemplos/industrial/catalogo" class="bg-[#82d0cf] px-6 py-4 text-sm font-semibold text-[#0e2634] hover:bg-[#a6e3e2]">Explorar catálogo técnico ↗</NuxtLink><a href="#aplicacoes" class="border border-slate-500 px-6 py-4 text-sm hover:bg-white/10">Conheça as aplicações ↓</a></div></div><div class="self-end border-l border-slate-500 pl-6 text-sm text-slate-300"><p class="text-xs uppercase tracking-widest text-[#80d2d2]">Da necessidade à especificação</p><p class="mt-5 leading-7">O produto certo começa<br>com informação clara.</p><p class="mt-8 text-[11px] text-slate-400">CATÁLOGO DEMONSTRATIVO<br>8 referências técnicas</p></div></div></section>
    <section class="mx-auto max-w-[1240px] px-6 py-16 md:py-20"><div class="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p class="text-xs uppercase tracking-[0.17em] text-[#418b8b]">Portfólio de produtos</p><h2 class="mt-3 font-heading text-3xl font-semibold tracking-tight md:text-4xl">Encontre sua linha de solução.</h2></div><NuxtLink to="/exemplos/industrial/catalogo" class="text-sm font-semibold">Ver todos os produtos →</NuxtLink></div><div class="grid gap-6 md:grid-cols-3"><NuxtLink v-for="family in productFamilies" :key="family.id" :to="`/exemplos/industrial/catalogo?familia=${family.id}`" class="group border border-slate-200"><div class="flex aspect-[1.4] items-center justify-center bg-[#f6f8f8] p-8"><img :src="family.image" :alt="family.name" width="500" height="400" loading="lazy" class="h-full w-full object-contain mix-blend-multiply transition-transform duration-300 group-hover:scale-105"></div><div class="p-6"><h3 class="flex justify-between gap-3 font-heading text-xl font-semibold">{{ family.name }} <span aria-hidden="true">↗</span></h3><p class="mt-3 text-base leading-7 text-slate-500">{{ family.description }}</p></div></NuxtLink></div></section>
    <section id="aplicacoes" class="bg-[#edf3f4] px-6 py-16 md:py-20"><div class="mx-auto grid max-w-[1192px] gap-12 md:grid-cols-[0.9fr_1.1fr]"><div><p class="text-xs uppercase tracking-[0.17em] text-[#418b8b]">Diferentes processos. Informações específicas.</p><h2 class="mt-5 font-heading text-3xl font-semibold leading-snug tracking-tight md:text-4xl">Entenda a aplicação.<br>Depois, o componente.</h2><p class="mt-6 text-base leading-7 text-slate-500">Pressão, temperatura, material e conexão fazem parte da conversa técnica. Um catálogo bem organizado aproxima o cliente dessas informações.</p></div><div><article v-for="item in applications" :key="item.number" class="flex gap-5 border-t border-slate-300 py-6"><span class="text-xs text-[#418b8b]">{{ item.number }}</span><div><h3 class="font-heading text-lg font-semibold">{{ item.title }}</h3><p class="mt-3 text-base leading-7 text-slate-500">{{ item.text }}</p></div></article></div></div></section>
    <QuoteList />
    <section id="empresa" class="mx-auto grid max-w-[1240px] gap-12 px-6 py-16 md:grid-cols-2 md:py-20"><div><p class="text-xs uppercase tracking-[0.17em] text-[#418b8b]">Conheça a Atlas</p><h2 class="mt-5 font-heading text-3xl font-semibold tracking-tight">Uma apresentação à altura<br>de um negócio técnico.</h2><p class="mt-6 text-base leading-7 text-slate-500">Atlas Industrial é uma empresa demonstrativa criada para mostrar como um fornecedor pode organizar sua presença digital: linhas de produtos, aplicações e documentação no mesmo lugar.</p></div><div class="border-l-4 border-[#82d0cf] bg-[#f6f8f8] p-8"><h3 class="text-lg font-semibold">Informações fáceis de consultar.</h3><ul class="mt-5 space-y-4 text-sm leading-6 text-slate-500"><li>✓ Busca pelo nome, modelo ou fabricante.</li><li>✓ Características técnicas lado a lado.</li><li>✓ Fichas em PDF vinculadas a cada produto.</li><li>✓ Um caminho direto para iniciar a conversa.</li></ul></div></section>
    <section id="contato" class="bg-[#163b50] px-6 py-14 text-white"><div class="mx-auto flex max-w-[1192px] flex-col justify-between gap-7 md:flex-row md:items-center"><div><p class="text-xs uppercase tracking-widest text-[#82d0cf]">Sua empresa industrial, bem apresentada</p><h2 class="mt-4 font-heading text-3xl font-semibold tracking-tight">Seu catálogo pode trabalhar pelo seu negócio.</h2><p class="mt-4 text-base text-slate-300">Converse com a Avyro sobre um site industrial e painel sob medida.</p></div><a :href="campaignWhatsapp('um site industrial com catálogo técnico e possibilidade de painel administrativo')" target="_blank" rel="noopener noreferrer" class="shrink-0 bg-white px-6 py-4 text-center text-sm font-semibold text-[#163b50] hover:bg-slate-100">Quero um site industrial ↗</a></div></section><IndustrialFooter />
  </div>
</template>
