<script setup lang="ts">
import { photoCategories } from '~/constants/photography'
const { category, favorites, onlyFavorites, visible, selectedId, selected, toggle, move, reset } = usePhotoPortfolio()
const viewer = ref<HTMLDialogElement | null>(null)
async function open(id: string): Promise<void> { selectedId.value = id; await nextTick(); viewer.value?.showModal() }
</script>
<template>
  <section id="colecoes" class="bg-[#e9e6df] px-6 py-20 text-[#23211e] md:px-12 md:py-28">
    <div class="mx-auto max-w-[1440px]">
      <div class="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><p class="text-sm uppercase tracking-[0.22em] text-[#877b69]">01 / Coleções em foco</p><h2 class="mt-5 font-['Playfair_Display'] text-5xl leading-tight md:text-7xl">Um olhar.<br><em>Muitas histórias.</em></h2></div><p class="max-w-sm text-base leading-8 text-[#776f64]">Percorra as imagens, veja cada detalhe e guarde as referências que mais conversam com você.</p></div>
      <div class="mt-10 flex flex-col justify-between gap-5 border-y border-[#bfb8ac] py-5 md:flex-row md:items-center"><div role="group" aria-label="Filtrar coleção" class="flex flex-wrap gap-5"><button v-for="item in photoCategories" :key="item" :aria-pressed="category === item" class="border-b-2 pb-2 text-sm transition-colors" :class="category === item ? 'border-[#a4432d] text-[#a4432d]' : 'border-transparent hover:border-[#877b69]'" @click="category = item">{{ item }}</button></div><button :aria-pressed="onlyFavorites" class="self-start rounded-full border px-5 py-3 text-sm" :class="onlyFavorites ? 'border-[#23211e] bg-[#23211e] text-white' : 'border-[#bfb8ac]'" @click="onlyFavorites = !onlyFavorites">{{ onlyFavorites ? '♥' : '♡' }} Minha seleção ({{ favorites.length }})</button></div>
      <p role="status" class="mt-5 text-sm text-[#776f64]">{{ visible.length }} {{ visible.length === 1 ? 'fotografia nesta seleção' : 'fotografias nesta seleção' }}</p>
      <div v-if="visible.length" class="mt-8 grid grid-cols-1 items-start gap-x-8 gap-y-12 md:grid-cols-2">
        <article v-for="(photo, i) in visible" :key="photo.id" :class="i % 2 === 1 ? 'md:mt-20' : ''">
          <div class="relative"><button :aria-label="`Ampliar ${photo.title}`" class="group block w-full overflow-hidden bg-[#d6d1c6]" @click="open(photo.id)"><img :src="photo.image" :alt="photo.alt" width="1400" height="1100" loading="lazy" class="w-full object-cover transition-transform duration-700 group-hover:scale-[1.025]" :class="photo.portrait ? 'aspect-[4/5]' : 'aspect-[1.4]'"><span class="absolute bottom-4 left-4 flex h-11 w-11 items-center justify-center rounded-full bg-white/90 text-xl" aria-hidden="true">↗</span></button><button :aria-label="`${favorites.includes(photo.id) ? 'Remover' : 'Adicionar'} ${photo.title} ${favorites.includes(photo.id) ? 'da' : 'à'} seleção`" :aria-pressed="favorites.includes(photo.id)" class="absolute right-4 top-4 flex h-11 w-11 items-center justify-center rounded-full bg-white/90 text-2xl text-[#a4432d]" @click="toggle(photo.id)">{{ favorites.includes(photo.id) ? '♥' : '♡' }}</button></div>
          <div class="mt-5 flex justify-between gap-4"><div><p class="text-xs uppercase tracking-[0.18em] text-[#877b69]">{{ photo.category }} / {{ photo.id }}</p><h3 class="mt-2 font-['Playfair_Display'] text-3xl">{{ photo.title }}</h3></div><span class="text-sm text-[#877b69]">↗</span></div><p class="mt-3 text-sm text-[#776f64]">Foto de <a :href="photo.source" target="_blank" rel="noopener noreferrer" class="underline underline-offset-4">{{ photo.author }}</a> · referência</p>
        </article>
      </div>
      <div v-else class="my-10 border border-dashed border-[#bfb8ac] p-12 text-center"><h3 class="font-['Playfair_Display'] text-3xl">Sua seleção ainda está em branco.</h3><p class="mt-4 text-base text-[#776f64]">Explore as coleções e toque no coração das suas imagens favoritas.</p><button class="mt-6 border-b border-[#23211e] pb-2 text-sm" @click="reset">Voltar a todas as imagens ↗</button></div>
      <p class="mt-12 max-w-2xl border-t border-[#bfb8ac] pt-5 text-sm leading-7 text-[#776f64]">Lume é um estúdio demonstrativo. As fotografias são referências dos autores indicados. Sua seleção fica apenas nesta visita e não é enviada.</p>
    </div>
    <dialog ref="viewer" aria-labelledby="photo-viewer-title" class="fixed inset-0 m-auto h-[94dvh] max-h-none w-[96vw] max-w-none bg-[#131311] p-4 text-[#e9e6df] md:p-6" @keydown.left.prevent="move(-1)" @keydown.right.prevent="move(1)">
      <div class="flex h-full flex-col"><div class="flex flex-wrap items-center justify-between gap-3 pb-4"><h2 id="photo-viewer-title" class="text-base">{{ selected.title }}</h2><button autofocus class="border border-white/30 px-4 py-2 text-sm" @click="viewer?.close()">Fechar ✕</button></div><img :src="selected.image" :alt="selected.alt" class="min-h-0 w-full flex-1 object-contain"><div class="flex flex-wrap items-center justify-between gap-4 pt-4"><p class="text-sm text-stone-400">{{ selected.category }} · Foto de {{ selected.author }}</p><div class="flex gap-3"><button aria-label="Fotografia anterior" class="h-11 w-11 border border-white/30" @click="move(-1)">←</button><button aria-label="Próxima fotografia" class="h-11 w-11 border border-white/30" @click="move(1)">→</button></div></div></div>
    </dialog>
  </section>
</template>
