import type { Config } from 'tailwindcss'

export default {
  content: [
    './app/**/*.{vue,ts}',
    './components/**/*.{vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f4f3fb',
        'on-secondary-container': '#003c64',
        'border-subtle': '#E9EEF5',
        'background': '#faf8ff',
        'on-secondary-fixed-variant': '#004a79',
        'on-error': '#ffffff',
        'error': '#ba1a1a',
        'primary-container': '#181b49',
        'on-tertiary-fixed': '#001e2d',
        'primary-fixed': '#e0e0ff',
        'on-primary-fixed': '#131644',
        'on-surface-variant': '#46464f',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
        'secondary-container': '#45a9fd',
        'tertiary-fixed-dim': '#7ed0ff',
        'on-background': '#1a1b21',
        'surface-variant': '#e3e1e9',
        'inverse-on-surface': '#f1f0f8',
        'on-tertiary': '#ffffff',
        'surface-light': '#FFFFFF',
        'surface-tint': '#575a8c',
        'secondary': '#00629f',
        'surface-bright': '#faf8ff',
        'on-secondary-fixed': '#001d34',
        'inverse-primary': '#c0c2fa',
        'primary': '#010133',
        'outline-variant': '#c7c5d0',
        'surface-container': '#eeedf5',
        'on-tertiary-container': '#0091c5',
        'error-container': '#ffdad6',
        'surface-dark': '#181B49',
        'inverse-surface': '#2f3036',
        'on-primary-fixed-variant': '#3f4272',
        'secondary-fixed-dim': '#9bcbff',
        'on-tertiary-fixed-variant': '#004c6a',
        'tertiary': '#000911',
        'secondary-fixed': '#d0e4ff',
        'primary-fixed-dim': '#c0c2fa',
        'on-primary-container': '#8184b8',
        'surface-container-high': '#e9e7ef',
        'surface-dim': '#dad9e1',
        'tertiary-fixed': '#c5e7ff',
        'surface-container-highest': '#e3e1e9',
        'on-secondary': '#ffffff',
        'outline': '#777680',
        'tertiary-container': '#002333',
        'on-primary': '#ffffff',
        'surface': '#faf8ff',
        'on-surface': '#1a1b21',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'section-padding-desktop': '120px',
        'container-max': '1280px',
        'margin-mobile': '16px',
        'gutter': '24px',
        'section-padding-mobile': '64px',
      },
      fontFamily: {
        'heading': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
} satisfies Config
