<script setup lang="ts">
import type { Prospect, ProspectActivityDraft } from '~/types/prospecting'
import { prospectStages, prospectChannels, prospectHeatClasses } from '~/constants/prospecting'
import { heat, heatReason, draftApproach, localDay, addDays } from '~/utils/prospecting'
const props = defineProps<{ lead: Prospect | null; log: (id: string, activity: ProspectActivityDraft) => boolean }>()
const emit = defineEmits<{ edit: [lead: Prospect]; archive: [id: string]; reopen: [id: string] }>()
const dialog = ref<HTMLDialogElement | null>(null)
const copied = ref(false)
const copyError = ref('')
const { draft, error, start, validate } = useProspectActivity()
watch(() => props.lead?.stage, (value, previous) => { if (previous === 'Não contatar' && value === 'Selecionado' && props.lead) start(props.lead) })
async function open(lead: Prospect) { start(lead); copied.value = false; copyError.value = ''; await nextTick(); dialog.value?.showModal() }
function submit() { const activity = validate(); if (activity && props.lead) { if (props.log(props.lead.id, activity)) { draft.value.note = ''; copied.value = false } else error.value = 'Não foi possível salvar. Confira a data, as permissões de armazenamento e o aviso no painel; seu texto foi mantido.' } }
function edit() { if (props.lead) { dialog.value?.close(); emit('edit', props.lead) } }
function archive() { if (props.lead) { emit('archive', props.lead.id); dialog.value?.close() } }
async function copy() { if (!props.lead) return; try { await navigator.clipboard.writeText(draftApproach(props.lead)); copied.value = true } catch { copyError.value = 'Não foi possível copiar automaticamente. Selecione o texto abaixo para copiar.' } }
defineExpose({ open })
</script>
<template>
  <dialog ref="dialog" aria-labelledby="prospect-detail-title" class="m-auto max-h-[94dvh] w-[min(1100px,96vw)] overflow-y-auto rounded-2xl bg-[#f7f9fc] p-5 text-slate-800 backdrop:bg-slate-950/50 sm:p-8">
    <div v-if="lead"><header class="flex flex-wrap items-start justify-between gap-5"><div><p class="text-xs uppercase tracking-widest text-slate-500">{{ lead.segment }} / {{ lead.city }}</p><h2 id="prospect-detail-title" class="mt-2 text-3xl font-semibold">{{ lead.company }}</h2><p class="mt-2 text-sm text-slate-500">{{ lead.person || 'Responsável ainda não identificado' }}</p></div><div class="flex gap-2"><button class="min-h-11 rounded-lg border bg-white px-4 text-sm" @click="edit">Editar</button><button autofocus class="min-h-11 rounded-lg border bg-white px-4 text-sm" @click="dialog?.close()">Fechar ✕</button></div></header><div class="mt-5 flex flex-wrap gap-2"><span class="rounded-full border px-3 py-2 text-xs" :class="prospectHeatClasses[heat(lead)]">{{ heat(lead) }}</span><span class="rounded-full bg-blue-50 px-3 py-2 text-xs text-blue-800">{{ lead.stage }}</span><span class="rounded-full bg-white px-3 py-2 text-xs">{{ lead.websiteStatus }}</span></div>
      <div class="mt-7 grid gap-7 lg:grid-cols-[0.9fr_1.1fr]"><div class="space-y-5"><section class="rounded-xl border bg-white p-5"><h3 class="text-sm font-semibold">Por que priorizar?</h3><p class="mt-3 text-sm leading-6 text-slate-600">{{ heatReason(lead) }}</p><ul class="mt-4 space-y-2 text-sm"><li>Atividade: {{ lead.activity }}</li><li>Avaliações: {{ lead.rating ?? '—' }} / 5 · {{ lead.reviewCount ?? '—' }} registros</li><li>{{ lead.goodReviews ? '✓' : '○' }} Boas avaliações · {{ lead.recentPhotos ? '✓' : '○' }} Fotos recentes</li></ul><p class="mt-4 whitespace-pre-wrap text-sm leading-7">{{ lead.opportunity || 'Nenhuma oportunidade registrada.' }}</p></section><section class="rounded-xl border bg-white p-5"><h3 class="text-sm font-semibold">Canais e referências</h3><p class="mt-3 break-words text-sm">{{ lead.phone || 'Telefone não informado' }}<br>{{ lead.email || 'E-mail não informado' }}</p><div class="mt-4 flex flex-wrap gap-3"><a v-if="lead.maps" :href="lead.maps" target="_blank" rel="noopener noreferrer" class="inline-flex min-h-11 items-center text-sm text-blue-700 underline">Google Maps ↗</a><a v-if="lead.instagram" :href="lead.instagram" target="_blank" rel="noopener noreferrer" class="inline-flex min-h-11 items-center text-sm text-blue-700 underline">Instagram ↗</a><a v-if="lead.website" :href="lead.website" target="_blank" rel="noopener noreferrer" class="inline-flex min-h-11 items-center text-sm text-blue-700 underline">Site atual ↗</a></div><p class="mt-3 text-xs text-slate-500">Encontrado em: {{ lead.source }}</p></section>
        <details v-if="lead.stage !== 'Não contatar'" class="rounded-xl border bg-white p-5"><summary class="min-h-11 cursor-pointer text-sm font-semibold">Preparar uma abordagem personalizada</summary><p class="mt-2 text-xs leading-6 text-slate-500">Revise as observações antes de usar. Copiar não envia nem registra um contato.</p><p class="mt-4 select-text whitespace-pre-wrap text-sm leading-7">{{ draftApproach(lead) }}</p><button class="mt-4 min-h-11 rounded-lg border px-4 text-sm" @click="copy">{{ copied ? 'Copiado ✓' : 'Copiar rascunho' }}</button><p v-if="copyError" role="status" class="mt-3 text-xs">{{ copyError }}</p></details><details class="rounded-xl border bg-white p-5"><summary class="min-h-11 cursor-pointer text-sm font-semibold">Notas e valores</summary><p class="mt-3 whitespace-pre-wrap text-sm leading-7">{{ lead.notes || 'Sem observações adicionais.' }}</p><p class="mt-4 text-sm">Projeto: {{ lead.proposalValue.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }) }}<br>Mensalidade: {{ lead.monthlyValue.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }) }}</p></details><button class="min-h-11 px-2 text-sm text-slate-500 underline" @click="archive">{{ lead.archived ? 'Restaurar contato' : 'Arquivar contato' }}</button></div>
        <div><section v-if="lead.stage === 'Não contatar'" class="rounded-xl border border-rose-200 bg-rose-50 p-5"><h3 class="font-semibold text-rose-900">Não contatar</h3><p class="mt-3 text-sm leading-7 text-rose-800">Este contato está fora dos retornos. Reabra somente se houver uma nova autorização ou contexto para o atendimento.</p><button class="mt-4 min-h-11 rounded-lg border border-rose-300 px-4 text-sm" @click="$emit('reopen', lead.id)">Reabrir acompanhamento</button></section><form v-else class="rounded-xl border bg-white p-5" @submit.prevent="submit"><h3 class="text-lg font-semibold">Registrar contato realizado</h3><p class="mt-2 text-xs leading-6 text-slate-500">WhatsApp primeiro, Instagram ou e-mail conforme o contexto. Retorno sugerido em dois dias, ajustável.</p><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="text-sm">Data do contato<input v-model="draft.date" type="date" :max="localDay()" required class="mt-2 min-h-12 w-full rounded-lg border px-3"></label><label class="text-sm">Canal<select v-model="draft.channel" class="mt-2 min-h-12 w-full rounded-lg border px-3"><option v-for="item in prospectChannels" :key="item">{{ item }}</option></select></label><label class="text-sm sm:col-span-2">Etapa após o contato<select v-model="draft.stage" class="mt-2 min-h-12 w-full rounded-lg border px-3"><option v-for="item in prospectStages.filter(item => item !== 'Selecionado')" :key="item">{{ item }}</option></select></label><label class="text-sm sm:col-span-2">O que aconteceu?<textarea v-model="draft.note" required maxlength="4000" rows="3" placeholder="Mensagem enviada, resposta recebida, dúvida, proposta…" class="mt-2 w-full rounded-lg border p-3" /></label><template v-if="!['Fechado', 'Sem interesse', 'Não contatar'].includes(draft.stage)"><label class="text-sm">Retornar em<input v-model="draft.followUp" type="date" :min="draft.date" class="mt-2 min-h-12 w-full rounded-lg border px-3"><button type="button" class="min-h-11 text-xs text-blue-700 underline" @click="draft.followUp = addDays(draft.date || localDay(), 2)">Dois dias após o contato</button></label><label class="text-sm">Próxima ação<input v-model="draft.nextAction" maxlength="500" class="mt-2 min-h-12 w-full rounded-lg border px-3"></label></template></div><p v-if="error" role="alert" class="mt-4 text-sm text-rose-700">{{ error }}</p><button class="mt-5 min-h-12 w-full rounded-lg bg-[#2458df] px-5 py-3 text-sm font-semibold text-white">Salvar interação</button></form>
          <section class="mt-6"><h3 class="text-lg font-semibold">Linha do tempo <span class="text-sm font-normal text-slate-500">({{ lead.history.length }})</span></h3><p v-if="!lead.history.length" class="mt-4 rounded-xl border border-dashed p-6 text-sm text-slate-500">Nenhum contato registrado. O histórico começa com a primeira abordagem.</p><ol v-else class="mt-5 space-y-4"><li v-for="item in [...lead.history].sort((a, b) => b.date.localeCompare(a.date))" :key="item.id" class="border-l-2 border-blue-200 bg-white p-4"><p class="text-xs text-slate-500">{{ item.date.split('-').reverse().join('/') }} · {{ item.channel }}</p><p class="mt-2 text-sm font-semibold">{{ item.stage }}</p><p class="mt-2 whitespace-pre-wrap text-sm leading-7 text-slate-600">{{ item.note }}</p></li></ol></section></div>
      </div>
    </div>
  </dialog>
</template>
