<script setup lang="ts">
import type { Prospect } from '~/types/prospecting'
import { prospectSegments } from '~/constants/prospecting'
import { heat, heatReason } from '~/utils/prospecting'
const props = defineProps<{ save: (lead: Prospect) => boolean }>()
const { draft, errors, start, validate } = useProspectEditor()
const dialog = ref<HTMLDialogElement | null>(null)
const editing = ref(false)
async function open(lead?: Prospect) { editing.value = !!lead; start(lead); await nextTick(); dialog.value?.showModal() }
function submit() { const record = validate(); if (record) { if (props.save(record)) dialog.value?.close(); else errors.value.save = 'Não foi possível salvar. Seus campos foram mantidos; confira o aviso do painel. Se houve alteração em outra aba, feche e reabra a ficha.' } }
defineExpose({ open })
</script>
<template>
  <dialog ref="dialog" aria-labelledby="lead-editor-title" class="m-auto max-h-[94dvh] w-[min(940px,96vw)] overflow-y-auto rounded-2xl bg-white p-0 text-slate-800 backdrop:bg-slate-950/50">
    <form v-if="draft" class="p-5 sm:p-8" novalidate @submit.prevent="submit">
      <div class="mb-7 flex items-start justify-between gap-4"><div><p class="text-xs uppercase tracking-widest text-blue-600">Ficha de prospecção</p><h2 id="lead-editor-title" class="mt-2 text-2xl font-semibold">{{ editing ? 'Editar empresa' : 'Adicionar empresa' }}</h2></div><button type="button" class="min-h-11 rounded-lg border px-4 text-sm" @click="dialog?.close()">Fechar ✕</button></div>
      <p v-if="Object.keys(errors).length" role="alert" class="mb-6 rounded-lg bg-rose-50 p-4 text-sm text-rose-800">{{ Object.values(errors).join(' ') }}</p>
      <fieldset><legend class="mb-4 text-sm font-semibold">01 / Empresa e localização</legend><div class="grid gap-4 sm:grid-cols-2">
        <label class="text-sm">Empresa *<input v-model="draft.company" autofocus maxlength="200" required class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3" :aria-invalid="!!errors.company"></label>
        <label class="text-sm">Pessoa de contato<input v-model="draft.person" maxlength="200" placeholder="Dono, gestora ou responsável" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"></label>
        <label class="text-sm">Cidade *<input v-model="draft.city" maxlength="200" required placeholder="Ex.: Osasco, SP" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3" :aria-invalid="!!errors.city"></label>
        <label class="text-sm">Segmento *<input v-model="draft.segment" list="prospect-segments" maxlength="200" required placeholder="Escolha ou digite" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"><datalist id="prospect-segments"><option v-for="item in prospectSegments" :key="item" :value="item" /></datalist></label>
        <label class="text-sm">Onde encontrou?<select v-model="draft.source" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"><option>Google Maps</option><option>Google</option><option>Instagram</option><option>Indicação</option><option>Visita local</option><option>Outro</option></select></label>
        <label class="text-sm">Telefone / WhatsApp<input v-model="draft.phone" maxlength="50" type="tel" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"></label>
        <label class="text-sm">E-mail<input v-model="draft.email" maxlength="254" type="email" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"></label>
        <label class="text-sm">Perfil no Google Maps<input v-model="draft.maps" type="url" placeholder="https://…" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"></label>
        <label class="text-sm">Instagram<input v-model="draft.instagram" type="url" placeholder="https://instagram.com/…" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"></label>
        <label class="text-sm">Site atual<input v-model="draft.website" type="url" placeholder="https://…" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"></label>
      </div></fieldset>
      <fieldset class="mt-8 border-t pt-6"><legend class="mb-4 pt-4 text-sm font-semibold">02 / Qualificação da oportunidade</legend><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm">Situação do site<select v-model="draft.websiteStatus" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"><option>Não verificado</option><option>Sem site</option><option>Só Instagram</option><option>Site antigo ou ruim</option><option>Site adequado</option></select></label><label class="text-sm">Atividade do negócio<select v-model="draft.activity" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"><option>Não verificada</option><option>Ativo</option><option>Aparentemente abandonado</option></select></label><label class="text-sm">Nota no Google (opcional)<input v-model.number="draft.rating" type="number" min="0" max="5" step="0.1" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"></label><label class="text-sm">Número de avaliações (opcional)<input v-model.number="draft.reviewCount" type="number" min="0" step="1" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"></label></div><div class="mt-4 flex flex-wrap gap-x-6 gap-y-2"><label class="flex min-h-11 items-center gap-2 text-sm"><input v-model="draft.goodReviews" type="checkbox" class="h-5 w-5">Boas avaliações</label><label class="flex min-h-11 items-center gap-2 text-sm"><input v-model="draft.recentPhotos" type="checkbox" class="h-5 w-5">Fotos recentes</label><label class="flex min-h-11 items-center gap-2 text-sm"><input v-model="draft.professional" type="checkbox" class="h-5 w-5">Apresentação profissional</label></div><div class="mt-4 grid gap-4 rounded-xl bg-slate-50 p-4 sm:grid-cols-2"><label class="text-sm">Prioridade<select v-model="draft.heatOverride" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 bg-white px-3"><option value="">Sugerir pelos critérios</option><option>Quente</option><option>Morno</option><option>Revisar</option><option>Descartar</option></select></label><p class="self-center text-sm leading-6"><strong>{{ heat(draft) }}</strong><br>{{ heatReason(draft) }}</p></div></fieldset>
      <fieldset class="mt-8"><legend class="mb-4 text-sm font-semibold">03 / Uma abordagem com contexto</legend><label class="block text-sm">Qual oportunidade você identificou?<textarea v-model="draft.opportunity" maxlength="4000" rows="3" placeholder="Ex.: os arranjos aparecem apenas no Instagram; um catálogo facilitaria a escolha." class="mt-2 w-full rounded-lg border border-slate-300 p-3" /></label><label class="mt-4 block text-sm">Frase personalizada para iniciar a conversa<textarea v-model="draft.personalization" maxlength="2000" rows="2" placeholder="Ex.: vi que vocês trabalham com arranjos e presentes em Osasco." class="mt-2 w-full rounded-lg border border-slate-300 p-3" /></label><label class="mt-4 block text-sm">Observações internas<textarea v-model="draft.notes" maxlength="6000" rows="3" class="mt-2 w-full rounded-lg border border-slate-300 p-3" /></label></fieldset>
      <fieldset class="mt-8"><legend class="mb-4 text-sm font-semibold">04 / Próximo passo e proposta</legend><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm">Próxima ação<input v-model="draft.nextAction" maxlength="500" placeholder="Ex.: falar com o responsável" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"></label><label class="text-sm">Data do retorno<input v-model="draft.followUp" type="date" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"></label><label class="text-sm">Valor do projeto (R$)<input v-model.number="draft.proposalValue" type="number" min="0" step="0.01" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"></label><label class="text-sm">Manutenção mensal (R$)<input v-model.number="draft.monthlyValue" type="number" min="0" step="0.01" class="mt-2 min-h-12 w-full rounded-lg border border-slate-300 px-3"></label></div><p class="mt-3 text-xs leading-6 text-slate-500">Para mudar a etapa, registre o contato na ficha da empresa. Valores de propostas só entram no total fechado quando a etapa for Fechado.</p></fieldset>
      <div class="mt-8 flex flex-wrap items-center justify-between gap-4 border-t pt-5"><p class="text-xs text-slate-500">* Campos obrigatórios · Salvo neste navegador</p><button class="min-h-12 rounded-lg bg-[#2458df] px-6 py-3 text-sm font-semibold text-white">Salvar empresa</button></div>
    </form>
  </dialog>
</template>
