<script setup lang="ts">
const niches = [
  { name: 'Marcenaria, esquadrias e marmoraria', signal: 'Projetos recentes, fotos próprias e atendimento por orçamento, mas portfólio difícil de consultar.', offer: 'Portfólio por ambiente, materiais e pedido de orçamento com contexto.', example: '/exemplos/marcenaria' },
  { name: 'Floriculturas e ateliês', signal: 'Arranjos e presentes publicados com frequência, enquanto o cliente precisa perguntar tudo por mensagem.', offer: 'Catálogo por ocasião, cuidados e apresentação das opções.', example: '/exemplos/floricultura' },
  { name: 'Climatização e serviços locais', signal: 'Empresa ativa, avaliações e região de atendimento claras, mas serviços pouco explicados na internet.', offer: 'Página de instalação e manutenção, cidades atendidas e contato para avaliação.', example: '/exemplos/climatizacao' },
  { name: 'Fornecedores industriais', signal: 'Produtos e marcas identificáveis, porém catálogo disperso em PDFs ou sem busca.', offer: 'Catálogo técnico, fichas por produto e seleção para cotação. Considere um ciclo comercial mais longo.', example: '/exemplos/industrial' },
  { name: 'Arquitetos e fotógrafos', signal: 'Trabalhos consistentes nas redes, mas falta um portfólio próprio que conte cada projeto.', offer: 'Coleções organizadas, apresentação do processo e contato para novos trabalhos.', example: '/exemplos/fotografia' },
]
const messages = [
  { title: '1. Pedir abertura para conversar', text: 'Olá, [nome]! Sou Samuel, da Avyro. Encontrei a [empresa] pesquisando [segmento] em [cidade] e vi [observação real e específica]. Percebi uma oportunidade em [ponto concreto]. Você é a pessoa que cuida dessa parte? Posso explicar a ideia em poucas linhas?' },
  { title: '2. Mostrar uma referência após o interesse', text: 'Pensei em organizar [produtos/serviços/projetos] para facilitar [benefício específico]. Este é um modelo demonstrativo, não um trabalho já feito para vocês: [link]. Para sua empresa, adaptaríamos a identidade, o conteúdo e os recursos. Hoje, o que mais dificulta apresentar esse trabalho aos clientes?' },
  { title: '3. Retomar uma conversa aberta', text: 'Oi, [nome]! Retomando nossa conversa sobre [objetivo]. Você conseguiu olhar a referência? Se fizer sentido, posso organizar o escopo para vocês avaliarem. Caso não seja prioridade agora, tudo bem: me avise para eu encerrar este retorno.' },
]
const copied = ref('')
async function copy(title: string, text: string) { try { await navigator.clipboard.writeText(text); copied.value = title } catch { copied.value = 'Selecione o texto para copiar manualmente.' } }
</script>
<template>
  <div class="space-y-7">
    <section class="rounded-2xl bg-[#14243e] p-6 text-white sm:p-9"><p class="text-xs uppercase tracking-widest text-blue-200">Seu roteiro de prospecção</p><h2 class="mt-4 max-w-3xl text-3xl font-semibold leading-tight">Procure uma oportunidade real.<br>Comece uma conversa útil.</h2><p class="mt-5 max-w-3xl text-sm leading-7 text-slate-300">O melhor lead combina negócio ativo, uma lacuna que seu site pode resolver e abertura para conversar. Estas são hipóteses para testar; nenhum segmento garante venda ou capacidade de pagamento.</p></section>
    <section class="rounded-2xl border bg-white p-6"><h2 class="text-xl font-semibold">Como escolher as próximas 30 empresas</h2><ol class="mt-6 grid gap-6 md:grid-cols-2"><li class="text-sm leading-7"><strong>01 / Uma cidade e poucos segmentos.</strong><br>Comece com até três segmentos e procure dez empresas de cada. Isso facilita comparar abordagens sem misturar públicos demais.</li><li class="text-sm leading-7"><strong>02 / Confirme antes de classificar.</strong><br>Pesquise o nome da empresa além do Maps. Um perfil sem link não prova que ela não tem site. Abra o Instagram e confira atividade recente.</li><li class="text-sm leading-7"><strong>03 / Registre uma oportunidade específica.</strong><br>Exemplo: “tem fotos de móveis recentes, mas não organiza projetos por ambiente”. Prefira isso a “o site é ruim”.</li><li class="text-sm leading-7"><strong>04 / Decida pelo conjunto dos sinais.</strong><br>Boas avaliações, fotos recentes, serviços claros e aparência profissional ajudam a priorizar. Confirme necessidade, responsável e orçamento na conversa.</li></ol></section>
    <section><h2 class="text-xl font-semibold">Perfis que vale testar primeiro</h2><p class="mt-3 text-sm leading-7 text-slate-500">Priorize a qualidade do contato dentro do nicho. Uma empresa ativa com uma necessidade clara vale mais que uma lista grande sem contexto.</p><div class="mt-6 grid gap-5 xl:grid-cols-2"><article v-for="niche in niches" :key="niche.name" class="rounded-2xl border bg-white p-6"><h3 class="text-lg font-semibold">{{ niche.name }}</h3><p class="mt-4 text-xs uppercase tracking-widest text-slate-500">Sinal para observar</p><p class="mt-2 text-sm leading-7">{{ niche.signal }}</p><p class="mt-4 text-xs uppercase tracking-widest text-slate-500">Ideia para apresentar</p><p class="mt-2 text-sm leading-7">{{ niche.offer }}</p><NuxtLink :to="niche.example" target="_blank" class="mt-4 inline-flex min-h-11 items-center text-sm text-blue-700 underline">Conhecer uma referência visual ↗</NuxtLink></article></div></section>
    <section class="rounded-2xl border bg-white p-6"><h2 class="text-xl font-semibold">Como abordar, registrar e acompanhar</h2><div class="mt-5 grid gap-6 lg:grid-cols-3"><div><h3 class="text-sm font-semibold">Antes do contato</h3><p class="mt-3 text-sm leading-7 text-slate-600">Use canais comerciais adequados. Número público não significa autorização para mensagens promocionais no WhatsApp. Nesse canal, obtenha a permissão necessária; não faça disparos em massa.</p></div><div><h3 class="text-sm font-semibold">Durante a conversa</h3><p class="mt-3 text-sm leading-7 text-slate-600">Apresente-se, cite algo que realmente observou e peça abertura. Entenda como chegam os clientes, quem decide e qual problema querem resolver. Mostre o modelo após o interesse; não prometa posição no Google ou vendas garantidas.</p></div><div><h3 class="text-sm font-semibold">Depois do contato</h3><p class="mt-3 text-sm leading-7 text-slate-600">Registre a interação realizada, canal, resultado e próxima ação. Retome no prazo combinado; dois dias é apenas uma sugestão para conversa aberta. Se houver recusa ou pedido de interrupção, encerre e marque “Não contatar”.</p></div></div></section>
    <section><h2 class="text-xl font-semibold">Rascunhos para adaptar</h2><p class="mt-3 text-sm text-slate-500">Troque todos os campos entre colchetes e use apenas informações verificadas. Copiar não envia mensagens.</p><div class="mt-5 space-y-4"><details v-for="message in messages" :key="message.title" class="rounded-xl border bg-white p-5"><summary class="min-h-11 cursor-pointer text-sm font-semibold">{{ message.title }}</summary><p class="mt-4 select-text whitespace-pre-wrap text-sm leading-8">{{ message.text }}</p><button class="mt-4 min-h-11 rounded-lg border px-4 text-sm" @click="copy(message.title, message.text)">{{ copied === message.title ? 'Copiado ✓' : 'Copiar rascunho' }}</button></details></div><p class="mt-2 text-xs" role="status">{{ copied && !messages.some(item => item.title === copied) ? copied : '' }}</p></section>
    <section class="grid gap-6 lg:grid-cols-2"><div class="rounded-2xl border bg-white p-6"><h2 class="text-xl font-semibold">Quando avançar uma etapa</h2><ul class="mt-5 space-y-3 text-sm leading-7"><li><strong>Contatado:</strong> você fez uma abordagem de verdade.</li><li><strong>Respondeu:</strong> recebeu uma resposta; silêncio não conta.</li><li><strong>Interessado:</strong> pediu referência, detalhes ou demonstrou necessidade.</li><li><strong>Proposta enviada:</strong> apresentou escopo e condições.</li><li><strong>Fechado:</strong> houve aceite das condições; registre projeto e mensalidade separadamente.</li></ul></div><div class="rounded-2xl border bg-white p-6"><h2 class="text-xl font-semibold">O que revisar antes de investir mais</h2><p class="mt-5 text-sm leading-7 text-slate-600">Compare empresas contatadas, respostas, interessados e fechamentos por segmento. Leia também as objeções: falta de prioridade, escopo, prazo, orçamento ou pessoa errada.</p><p class="mt-4 text-sm leading-7 text-slate-600">Se houver poucos resultados, ajuste uma variável por vez: seleção, mensagem ou oferta. Manutenção mensal é uma opção com atividades definidas; não inclua recorrência como se já estivesse contratada.</p><p class="mt-4 text-xs leading-6 text-slate-500">Uma amostra de dez empresas é aprendizado inicial, não um ranking definitivo dos melhores nichos.</p></div></section>
    <p class="text-xs leading-6 text-slate-500">Base: sua conversa “Comparar prospecção e anúncios”, adaptada à rotina deste painel. Regras do canal: <a href="https://business.whatsapp.com/policy" target="_blank" rel="noopener noreferrer" class="underline">Política de mensagens do WhatsApp Business</a>.</p>
  </div>
</template>
