<script setup lang="ts">
import { campaignWhatsapp } from '~/utils/campaign'
const steps = [
  { title: 'A gente conversa.', text: 'Entendemos sua empresa, seus clientes e o que você espera do site.' },
  { title: 'Você recebe uma proposta.', text: 'Escopo, investimento e condições definidos para o seu projeto.' },
  { title: 'Seu site ganha forma.', text: 'Criamos, apresentamos para revisão e preparamos a entrega.' },
  { title: 'Seguimos juntos, se quiser.', text: 'Você pode contratar manutenção mensal depois do lançamento.' },
]
</script>
<template>
  <section id="processo" class="mx-auto max-w-[1240px] px-5 py-16 md:px-8 md:py-24"><div class="flex flex-col justify-between gap-6 md:flex-row"><h2 class="font-heading text-3xl font-semibold tracking-[-0.04em] md:text-[42px]">Próximo passo.<br>Sem complicar.</h2><p class="max-w-sm text-base leading-7 text-slate-500">Você conhece seu negócio. A gente transforma essa história em uma experiência digital.</p></div><ol class="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4"><li v-for="(step, index) in steps" :key="step.title" class="border-t border-slate-200 pt-5"><span class="text-xs font-semibold text-[#255bef]">0{{ index + 1 }}</span><h3 class="mt-6 font-heading text-lg font-semibold">{{ step.title }}</h3><p class="mt-3 text-base leading-7 text-slate-500">{{ step.text }}</p></li></ol></section>
  <section class="border-y border-slate-200 bg-[#fafbfc] px-5 py-12 md:px-8"><div class="mx-auto grid max-w-[1176px] gap-10 md:grid-cols-[1fr_1.2fr]"><div><p class="text-xs uppercase tracking-[0.17em] text-slate-400">Trabalhos & experiência</p><h2 class="mt-4 font-heading text-2xl font-semibold tracking-tight">Projetos que já saíram do papel.</h2><p class="mt-3 text-base leading-7 text-slate-500">Kamui Card Game · Martins Representações</p><video src="/videos/Record_2026-07-12-18-25-38.mp4" controls preload="none" playsinline aria-label="Apresentação do site Martins Representações" class="mt-5 aspect-video w-full rounded-lg bg-slate-900" /></div><div class="self-center"><div class="grid grid-cols-2 gap-6 border-b border-slate-200 pb-6"><div><p class="font-heading text-3xl font-semibold">+100</p><p class="mt-1 text-xs text-slate-500">Projetos entregues</p></div><div><p class="font-heading text-3xl font-semibold">98%</p><p class="mt-1 text-xs text-slate-500">Clientes satisfeitos</p></div></div><blockquote class="mt-6 text-base leading-8 text-slate-600">“A equipe da Avyro Growth Company transformou nossa presença digital. Nosso novo site não apenas ficou incrível esteticamente, mas também dobrou nosso volume de orçamentos no primeiro mês.”</blockquote><p class="mt-4 text-base font-semibold">Carlos Eduardo <span class="font-normal text-slate-400">· CEO, TechSolutions</span></p></div></div></section>
  <section id="orcamento" class="px-5 py-16 md:px-8 md:py-24"><div id="contact" class="mx-auto flex max-w-[1176px] flex-col justify-between gap-8 rounded-2xl bg-[#101c35] p-8 text-white md:flex-row md:items-center md:p-14"><div><p class="text-xs uppercase tracking-[0.17em] text-blue-300">Vamos construir seu próximo passo?</p><h2 class="mt-5 max-w-xl font-heading text-3xl font-semibold leading-tight tracking-[-0.04em] md:text-[40px]">Conte sobre sua empresa.<br>Vamos pensar no seu site.</h2><p class="mt-5 max-w-lg text-base leading-7 text-slate-400">Cada projeto tem seu tamanho, seus objetivos e suas possibilidades. A proposta também.</p></div><div class="shrink-0"><a :href="campaignWhatsapp()" target="_blank" rel="noopener noreferrer" class="inline-flex items-center gap-5 rounded-lg bg-white px-6 py-4 text-sm font-semibold text-[#101c35] transition-colors hover:bg-blue-100">Vamos conversar ↗</a><p class="mt-4 text-xs text-slate-400">WhatsApp · (11) 95137-2631</p></div></div></section>
</template>
