<script setup lang="ts">
import ModelPreview from './ModelPreview.vue'
const tabs = ['Fotografias', 'Estudo espacial 3D', 'Materiais']
const tab = ref('Fotografias')
const photos = ['/images/campaign/architecture-1.jpg', '/images/campaign/architecture-2.jpg', '/images/campaign/architecture-3.jpg']
const photo = ref(0)
const material = ref('Madeira natural')
</script>
<template>
  <section id="caderno-espacial" class="bg-[#deded5] px-5 py-16 md:px-12 md:py-24"><div class="mx-auto max-w-7xl"><div class="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p class="text-xs uppercase tracking-[0.2em]">Caderno aberto / matéria e espaço</p><h2 class="mt-5 font-heading text-4xl tracking-tight md:text-5xl">Entre o olhar e o volume.</h2></div><p class="max-w-sm text-sm leading-7 text-stone-600">Fotografias de referência, um estudo tridimensional e uma paleta para explorar a linguagem do projeto.</p></div><div class="my-8 flex flex-wrap gap-3" role="group" aria-label="Modos de explorar o projeto"><button v-for="item in tabs" :key="item" :aria-pressed="tab === item" class="min-h-12 border-b px-4 py-3 text-sm" :class="tab === item ? 'border-stone-900 font-semibold' : 'border-transparent text-stone-600'" @click="tab = item">{{ item }}</button></div><div v-if="tab === 'Fotografias'"><img :src="photos[photo]" :alt="`Fotografia de referência arquitetônica ${photo + 1}`" width="1400" height="900" loading="lazy" class="aspect-[4/3] w-full object-cover md:aspect-[2]"><div class="mt-4 flex gap-3" role="group" aria-label="Fotografias de arquitetura"><button v-for="(_, i) in photos" :key="i" :aria-pressed="photo === i" class="h-12 w-12 border border-stone-400" :class="photo === i ? 'bg-stone-800 text-white' : ''" @click="photo = i">0{{ i + 1 }}</button></div></div><div v-else-if="tab === 'Estudo espacial 3D'"><ModelPreview kind="room" /><p class="mt-4 text-sm text-stone-600">Ambiente conceitual independente das fotografias. Explore a distribuição dos volumes por diferentes ângulos.</p></div><div v-else class="grid gap-8 md:grid-cols-2"><img src="/images/campaign/wood-kitchen.jpg" alt="Referência de madeira em um ambiente residencial" width="1000" height="800" loading="lazy" class="aspect-[4/3] w-full object-cover"><div class="self-center"><p class="text-xs uppercase tracking-widest">Paleta de referência</p><div class="my-6 flex flex-wrap gap-3"><button v-for="item in ['Madeira natural', 'Pedra clara', 'Verde mineral']" :key="item" :aria-pressed="material === item" class="min-h-12 border px-4 py-3 text-sm" :class="material === item ? 'border-stone-900 bg-stone-100' : 'border-stone-400'" @click="material = item">{{ item }}</button></div><h3 class="text-3xl" aria-live="polite">{{ material }}</h3><p class="mt-4 text-base leading-8 text-stone-600">{{ material === 'Madeira natural' ? 'Textura e tons quentes para aproximar o ambiente da natureza.' : material === 'Pedra clara' ? 'Uma base de tons suaves para acompanhar a luz e equilibrar os contrastes.' : 'Uma presença discreta de cor, em diálogo com folhagens e materiais naturais.' }}</p></div></div></div></section>
</template>
