<script setup lang="ts">
import { floralProducts } from '~/constants/florist'
const { current, index, choose } = useDemoChoice(floralProducts)
const space = ref('Em casa')
const palette = ref('Terra')
const palettes: Record<string, string[]> = { Terra: ['#aa795d', '#d3baa0', '#ebe2d6'], Jardim: ['#526148', '#a0ad89', '#dfdfc8'], Bruma: ['#889b9d', '#c4ceca', '#ecefe8'] }
const spaces: Record<string, string> = { 'Em casa': '/images/campaign/wood-kitchen.jpg', 'Na recepção': '/images/campaign/architecture-2.jpg', 'No encontro': '/images/campaign/architecture-3.jpg' }
</script>
<template>
  <section id="painel-botanico" class="bg-[#dce0d1] px-5 py-16 md:px-10 md:py-24"><div class="mx-auto max-w-6xl"><p class="text-xs uppercase tracking-[0.2em]">Caderno de atmosferas</p><h2 class="mt-5 font-['Playfair_Display'] text-4xl md:text-5xl">O seu espaço.<br><em>Uma nova composição.</em></h2><div class="mt-10 grid gap-8 lg:grid-cols-[1.3fr_1fr]"><div class="bg-[#f6f4eb] p-5 shadow-sm sm:p-8"><div class="grid grid-cols-[1.2fr_1fr] items-start gap-3"><img :src="current.image" :alt="current.alt" width="700" height="900" loading="lazy" class="aspect-[3/4] w-full object-cover"><div class="pt-7"><img :src="spaces[space]" :alt="`Referência de ambiente: ${space}`" width="600" height="600" loading="lazy" class="aspect-square w-full object-cover"><p class="mt-4 font-['Playfair_Display'] text-lg italic">{{ space }}</p></div></div><div class="mt-6 flex gap-3" aria-label="Paleta escolhida"><span v-for="color in palettes[palette]" :key="color" class="h-14 flex-1" :style="{ background: color }" /></div><p class="mt-6 border-t border-stone-300 pt-4 text-sm" aria-live="polite">{{ current.name }} / {{ palette }} / {{ space }}</p><p class="mt-2 text-[10px] uppercase tracking-[0.2em] text-stone-500">Casa Flora — um estudo de atmosfera</p></div><div class="self-center"><fieldset><legend class="mb-3 text-sm font-semibold">A presença floral</legend><div class="grid grid-cols-2 gap-2"><button v-for="(flower, i) in floralProducts" :key="flower.id" :aria-pressed="index === i" class="min-h-12 border px-3 py-3 text-left text-sm" :class="index === i ? 'border-[#343e31] bg-[#f6f4eb]' : 'border-[#a5af99]'" @click="choose(i)">{{ flower.name }}</button></div></fieldset><fieldset class="mt-7"><legend class="mb-3 text-sm font-semibold">A paleta</legend><div class="flex flex-wrap gap-2"><button v-for="(_, name) in palettes" :key="name" :aria-pressed="palette === name" class="min-h-12 border px-4 text-sm" :class="palette === name ? 'border-[#343e31] bg-[#f6f4eb]' : 'border-[#a5af99]'" @click="palette = name">{{ name }}</button></div></fieldset><label class="mt-7 block text-sm font-semibold" for="moodboard-space">O lugar</label><select id="moodboard-space" v-model="space" class="mt-3 min-h-12 w-full border border-[#a5af99] bg-[#f6f4eb] px-3 text-base"><option v-for="(_, name) in spaces" :key="name">{{ name }}</option></select><p class="mt-6 text-sm leading-7 text-[#6a745f]">Mude uma escolha e observe como as referências conversam entre si. Este painel reúne inspirações, sem simular a instalação das flores no ambiente.</p><p class="mt-4 text-xs text-[#6a745f]">Seleção temporária, sem envio.</p></div></div></div></section>
</template>
