<script setup lang="ts">
import { floralProducts } from '~/constants/florist'
const { current, index, choose } = useDemoChoice(floralProducts)
const packaging = ref('Papel natural')
const message = ref('Que seu dia floresça com coisas boas.')
const packagingColors: Record<string, string> = { 'Papel natural': '#c8ad8c', 'Rosa suave': '#e5bfc8', 'Verde sálvia': '#a9b7a1' }
</script>
<template>
  <section id="presente-sob-medida" class="bg-[#f0d6db] px-5 py-16 sm:px-8 md:py-24"><div class="mx-auto max-w-6xl"><p class="text-xs uppercase tracking-[0.2em]">Um presente, do seu jeito</p><h2 class="mt-4 font-['Playfair_Display'] text-4xl sm:text-5xl">Escolha as flores.<br><em>Assine o sentimento.</em></h2><div class="mt-10 grid gap-8 lg:grid-cols-2"><div class="overflow-hidden rounded-t-[120px] bg-[#fffaf5] p-5 sm:p-8" :style="{ borderBottom: `18px solid ${packagingColors[packaging]}` }"><img :src="current.image" :alt="current.alt" width="800" height="950" loading="lazy" class="aspect-[4/5] max-h-[430px] w-full rounded-t-[100px] object-cover"><div class="mx-2 -rotate-2 border border-[#ecdde0] bg-white p-5 shadow-sm"><p class="text-[10px] uppercase tracking-widest">Para alguém especial</p><p class="mt-4 whitespace-pre-wrap break-words font-['Playfair_Display'] text-xl italic leading-8">{{ message || 'Seu carinho começa com uma palavra…' }}</p><p class="mt-5 text-xs">com afeto ✳</p></div><p class="mt-6 text-center text-xs" aria-live="polite">{{ current.name }} · {{ packaging }}</p></div><div class="self-center"><fieldset><legend class="mb-4 text-sm font-semibold">01 / Qual composição combina com a pessoa?</legend><div class="grid grid-cols-3 gap-3"><button v-for="(flower, i) in floralProducts" :key="flower.id" :aria-pressed="index === i" class="overflow-hidden rounded-lg border-2 text-left" :class="index === i ? 'border-[#792d49]' : 'border-transparent'" @click="choose(i)"><img :src="flower.image" :alt="flower.alt" width="180" height="160" loading="lazy" class="aspect-square w-full object-cover"><span class="block bg-[#fffaf5] p-2 text-[11px] leading-5">{{ flower.name }}</span></button></div></fieldset><fieldset class="mt-7"><legend class="mb-3 text-sm font-semibold">02 / Paleta da embalagem</legend><div class="flex flex-wrap gap-2"><button v-for="(color, name) in packagingColors" :key="name" :aria-pressed="packaging === name" class="inline-flex min-h-12 items-center gap-2 rounded-full border px-4 text-sm" :class="packaging === name ? 'border-[#792d49] bg-white' : 'border-[#b98b9b]'" @click="packaging = name"><span class="h-4 w-4 rounded-full" :style="{ background: color }" />{{ name }}</button></div></fieldset><label for="gift-message" class="mb-3 mt-7 block text-sm font-semibold">03 / Seu cartão</label><textarea id="gift-message" v-model="message" maxlength="180" rows="3" class="w-full rounded-lg border border-[#b98b9b] bg-[#fffaf5] p-4 text-base" /><p class="mt-2 text-right text-xs">{{ message.length }}/180</p><p class="mt-5 text-xs leading-6 text-[#805464]">Prévia de combinação: a faixa de cor representa a paleta da embalagem. A fotografia do buquê é ilustrativa. Nada é comprado ou enviado.</p></div></div></div></section>
</template>
