<script setup lang="ts">
import { portfolioPhotos } from '~/constants/photography'
const { current, index, choose } = useDemoChoice(portfolioPhotos)
const viewer = ref<HTMLDialogElement | null>(null)
function move(delta: number) { choose((index.value + delta + portfolioPhotos.length) % portfolioPhotos.length) }
</script>
<template>
  <section class="bg-[#24241f] px-5 py-16 md:px-12 md:py-24"><div class="mx-auto max-w-6xl"><p class="text-xs uppercase tracking-[0.25em] text-[#b6a991]">Uma pausa para olhar</p><h2 class="mt-5 font-['Playfair_Display'] text-4xl md:text-6xl">A imagem ocupa.<br><em>A história permanece.</em></h2><div class="relative mt-9"><img :src="current.image" :alt="current.alt" width="1400" height="950" loading="lazy" class="aspect-[4/3] w-full object-cover md:aspect-[2]"><button class="absolute bottom-4 right-4 min-h-12 rounded-full bg-[#e9e6df] px-5 py-3 text-sm text-[#24241f]" @click="viewer?.showModal()">Entrar no ensaio ↗</button></div><p class="mt-4 text-xs leading-6 text-[#b6a991]">Seleção editorial de referências de diferentes autores; não representa um ensaio de autoria do Lume.</p></div>
    <dialog ref="viewer" aria-labelledby="essay-title" class="fixed inset-0 m-auto h-[94dvh] w-[96vw] max-w-none bg-[#11110f] p-4 text-[#eee8dc] md:p-7" @keydown.left.prevent="move(-1)" @keydown.right.prevent="move(1)"><div class="flex h-full flex-col gap-4"><div class="flex items-center justify-between gap-4"><p id="essay-title" class="text-xs uppercase tracking-[0.2em]">Lume / Caderno de olhares</p><button autofocus class="min-h-11 border border-white/30 px-4 text-sm" @click="viewer?.close()">Fechar ✕</button></div><img :key="current.id" :src="current.image" :alt="current.alt" class="min-h-0 w-full flex-1 object-contain"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div aria-live="polite"><p class="font-['Playfair_Display'] text-xl sm:text-3xl">{{ current.title }}</p><p class="mt-2 text-xs text-stone-400">Foto de <a :href="current.source" target="_blank" rel="noopener noreferrer" class="underline">{{ current.author }}</a></p></div><div class="flex items-center gap-5"><button aria-label="Imagem anterior do ensaio" class="h-12 w-12 border border-white/30" @click="move(-1)">←</button><span class="text-sm">{{ index + 1 }} / {{ portfolioPhotos.length }}</span><button aria-label="Próxima imagem do ensaio" class="h-12 w-12 border border-white/30" @click="move(1)">→</button></div></div><div class="flex gap-2" role="group" aria-label="Escolher imagem do ensaio"><button v-for="(photo, i) in portfolioPhotos" :key="photo.id" :aria-label="photo.title" :aria-pressed="index === i" class="min-h-11 flex-1 border-b-2" :class="index === i ? 'border-[#c6a27b]' : 'border-white/20'" @click="choose(i)"><span class="sr-only">{{ i + 1 }}</span></button></div></div></dialog>
  </section>
</template>
