<script setup lang="ts">
import ModelPreview from './ModelPreview.vue'
const woods = [{ name: 'Carvalho', color: '#b59168' }, { name: 'Nogueira', color: '#694633' }, { name: 'Freijó', color: '#bc834e' }]
const doors = [{ name: 'Areia', color: '#d4c9b7' }, { name: 'Oliva', color: '#697460' }, { name: 'Grafite', color: '#3c4140' }]
const wood = ref(woods[0]!)
const door = ref(doors[0]!)
const handles = ref(true)
const exploded = ref(false)
</script>
<template>
  <section id="atelier-3d" class="bg-[#e8e0d3] px-5 py-16 md:px-12 md:py-24"><div class="mx-auto max-w-6xl"><p class="text-xs uppercase tracking-[0.2em]">Ateliê de escolhas / 3D</p><h2 class="mt-4 font-['Playfair_Display'] text-4xl md:text-5xl">Seu olhar. Seu acabamento.</h2><p class="mt-5 max-w-xl text-base leading-7 text-[#706252]">Experimente combinações de estrutura, portas e puxadores em um aparador desenhado para este estudo.</p><div class="mt-10 grid gap-7 lg:grid-cols-[1fr_300px]"><ModelPreview kind="cabinet" :finish="wood.color" :accent="door.color" :handles="handles" :exploded="exploded" /><div class="space-y-6 bg-[#faf7f1] p-6"><fieldset><legend class="mb-3 text-sm font-semibold">01 / Estrutura</legend><button v-for="item in woods" :key="item.name" :aria-pressed="wood.name === item.name" class="mr-2 mb-2 min-h-11 border px-3 py-2 text-sm" :class="wood.name === item.name ? 'border-[#463d32] bg-[#e8e0d3]' : 'border-[#ccc3b6]'" @click="wood = item">{{ item.name }}</button></fieldset><fieldset><legend class="mb-3 text-sm font-semibold">02 / Portas</legend><button v-for="item in doors" :key="item.name" :aria-pressed="door.name === item.name" class="mr-2 mb-2 inline-flex min-h-11 items-center gap-2 border px-3 py-2 text-sm" :class="door.name === item.name ? 'border-[#463d32]' : 'border-[#ccc3b6]'" @click="door = item"><span class="h-4 w-4 rounded-full" :style="{ background: item.color }" />{{ item.name }}</button></fieldset><label class="flex min-h-11 items-center gap-3 text-sm"><input v-model="handles" type="checkbox" class="h-5 w-5">Puxadores metálicos</label><label class="flex min-h-11 items-center gap-3 text-sm"><input v-model="exploded" type="checkbox" class="h-5 w-5">Separar portas da estrutura</label><p class="border-t border-[#ccc3b6] pt-5 text-sm leading-7" aria-live="polite">{{ wood.name }} + {{ door.name }}<br>{{ handles ? 'Com puxadores' : 'Frente sem puxadores' }}</p></div></div><p class="mt-5 text-xs leading-6 text-[#706252]">Modelo tridimensional ilustrativo. Cores digitais aproximadas; materiais, ferragens e medidas dependem do projeto real.</p></div></section>
</template>
