import type { DemoProject } from '~/types/campaign'

export const demoProjects: DemoProject[] = [
  { slug: 'industrial', name: 'Atlas Industrial', segment: 'INDÚSTRIA & INSTRUMENTAÇÃO', summary: 'Produtos organizados, informações técnicas e um caminho direto até a cotação.', image: '/images/campaign/industrial.jpg', imageAlt: 'Instalação industrial com tubulações e equipamentos', color: '#163b50', number: '01' },
  { slug: 'arquitetura', name: 'ArchStudio', segment: 'ARQUITETURA & INTERIORES', summary: 'Uma apresentação editorial que dá espaço para cada projeto contar sua história.', image: '/images/campaign/architecture-1.jpg', imageAlt: 'Casa contemporânea integrada ao jardim', color: '#44403c', number: '02' },
  { slug: 'manicure', name: 'BellaNails', segment: 'BELEZA & CUIDADO', summary: 'Serviços, detalhes e inspiração para transformar uma visita em uma conversa.', image: '/images/campaign/nails-hero.jpg', imageAlt: 'Detalhe de unhas e esmaltação', color: '#934354', number: '03' },
  { slug: 'oficina', name: 'AutoElite', segment: 'SERVIÇOS AUTOMOTIVOS', summary: 'O serviço certo, explicado com clareza. Atendimento começa antes da oficina.', image: '/images/campaign/workshop.jpg', imageAlt: 'Profissional trabalhando em uma oficina automotiva', color: '#9a5509', number: '04' },
  { slug: 'climatizacao', name: 'Brisa Climatização', segment: 'CLIMATIZAÇÃO & CONFORTO', summary: 'Ambientes, instalação e manutenção em uma experiência leve e guiada.', image: '/images/campaign/climate.jpg', imageAlt: 'Ar-condicionado instalado em ambiente interno', color: '#428e98', number: '05' },
  { slug: 'odontologia', name: 'Serena Odontologia', segment: 'ODONTOLOGIA & CUIDADO', summary: 'Uma jornada acolhedora para conhecer os cuidados e a primeira visita.', image: '/images/campaign/dental-care.jpg', imageAlt: 'Conversa em ambiente odontológico', color: '#819383', number: '06' },
  { slug: 'contabilidade', name: 'Nexo Contabilidade', segment: 'CONTABILIDADE & NEGÓCIOS', summary: 'Roteiros para abertura, migração e acompanhamento da empresa.', image: '/images/campaign/accounting.jpg', imageAlt: 'Computador com informações e gráficos de negócios', color: '#193e34', number: '07' },
  { slug: 'marcenaria', name: 'Veio Marcenaria', segment: 'MARCENARIA & PLANEJADOS', summary: 'Ambientes e acabamentos para explorar a personalidade de cada projeto.', image: '/images/campaign/wood-kitchen.jpg', imageAlt: 'Cozinha com móveis em madeira', color: '#88745a', number: '08' },
  { slug: 'engenharia', name: 'Prumo Engenharia', segment: 'ENGENHARIA & REFORMAS', summary: 'Da preparação à entrega, etapas e responsabilidades apresentadas com clareza.', image: '/images/campaign/construction.jpg', imageAlt: 'Canteiro de obra em construção', color: '#8a583f', number: '09' },
  { slug: 'fotografia', name: 'Lume Fotografia', segment: 'FOTOGRAFIA & HISTÓRIAS', summary: 'Coleções imersivas, galeria editorial e seleção de imagens para valorizar cada olhar.', image: '/images/campaign/photo-landscape.jpg', imageAlt: 'Camadas de montanhas ao entardecer', color: '#a4432d', number: '10' },
  { slug: 'floricultura', name: 'Afeto Flores', segment: 'FLORICULTURA & PRESENTES', summary: 'Catálogo por ocasião, seleção de flores e um cartão com a sua mensagem.', image: '/images/campaign/flowers-bouquet.jpg', imageAlt: 'Buquê de flores em tons rosados', color: '#792d49', number: '11' },
  { slug: 'floricultura-atelie', name: 'Casa Flora', segment: 'ATELIÊ FLORAL & CURADORIA', summary: 'Coleção botânica editorial e uma experiência de flores para a rotina.', image: '/images/campaign/flowers-window.jpg', imageAlt: 'Flores em um vaso junto à janela', color: '#343e31', number: '12' },
]
