<script setup lang="ts">
import ArchitectureReading from '~/components/campaign/ArchitectureReading.vue'
import Gallery from '~/components/campaign/Gallery.vue'
import { campaignWhatsapp } from '~/utils/campaign'
import type { GalleryImage } from '~/types/campaign'
definePageMeta({ layout: 'demonstracao' })
useDemoSeo('ArchStudio — espaços para viver', 'Demonstração editorial para arquitetura e interiores. Projetos, materiais e formas de habitar.')
const images: GalleryImage[] = [
  { src: '/images/campaign/architecture-1.jpg', alt: 'Residência contemporânea com jardim e grandes aberturas', caption: '01 — Casa Jardim / Residencial' },
  { src: '/images/campaign/architecture-2.jpg', alt: 'Interior residencial com materiais naturais e luz', caption: '02 — Entre Luz / Interiores' },
  { src: '/images/campaign/architecture-3.jpg', alt: 'Espaço residencial contemporâneo', caption: '03 — Casa Horizonte / Residencial' },
]
</script>
<template>
  <div class="bg-[#f3f2ee] text-[#252724]">
    <header class="flex flex-wrap items-center justify-between gap-5 border-b border-stone-300 px-6 py-7 md:px-12"><NuxtLink to="/exemplos/arquitetura" class="font-heading text-2xl font-medium tracking-[-0.06em]">arch/studio</NuxtLink><nav class="flex gap-6 text-[11px] uppercase tracking-[0.15em]" aria-label="ArchStudio"><a href="#projetos" class="hover:underline">Projetos</a><a href="#estudio" class="hover:underline">Estúdio</a><a href="#contato" class="hover:underline">Contato ↗</a></nav></header>
    <section class="px-6 pb-12 pt-12 md:px-12 md:pt-20"><div class="flex flex-col justify-between gap-8 pb-10 lg:flex-row lg:items-end"><h1 class="font-heading text-5xl font-normal leading-[1.04] tracking-[-0.065em] sm:text-7xl lg:text-[94px]">Espaços para viver.<br><span class="text-stone-400">Arquitetura para sentir.</span></h1><p class="max-w-[250px] text-xs leading-6 text-stone-500">O encontro entre matéria, luz e cotidiano.<br>Arquitetura & interiores.</p></div><img src="/images/campaign/architecture-1.jpg" alt="Residência contemporânea com jardim e integração entre espaços" width="1800" height="1000" fetchpriority="high" class="aspect-[1.35] w-full object-cover md:aspect-[2.1]"><div class="mt-4 flex justify-between gap-5 text-[11px] uppercase tracking-widest text-stone-500"><span>Estudo residencial — Casa Jardim</span><a href="#projetos" class="text-stone-800">Conhecer os projetos ↓</a></div></section>
    <section id="estudio" class="mx-6 grid gap-10 border-t border-stone-300 py-16 md:mx-12 md:grid-cols-[1fr_2fr] md:py-24"><p class="text-xs uppercase tracking-[0.17em] text-stone-500">01 / Nossa forma de pensar</p><div><h2 class="max-w-4xl font-heading text-3xl font-normal leading-[1.4] tracking-tight md:text-5xl">Antes de desenhar um espaço,<br>é preciso entender <span class="text-stone-400">a vida que vai acontecer nele.</span></h2><div class="mt-10 grid max-w-3xl gap-7 text-sm leading-7 text-stone-500 md:grid-cols-2"><p>A arquitetura começa na escuta. Na maneira como você chega em casa, recebe pessoas e encontra tempo para si.</p><p>Materialidade, luz natural e proporção orientam cada escolha. Um projeto que responde ao lugar e a quem o habita.</p></div></div></section>
    <section id="projetos" class="bg-[#242723] px-6 py-16 text-[#f3f2ee] md:px-12 md:py-20"><div class="mb-12 flex items-end justify-between gap-5"><div><p class="text-xs uppercase tracking-[0.18em] text-stone-400">02 / Seleção de estudos</p><h2 class="mt-4 font-heading text-4xl font-normal tracking-tight md:text-6xl">Cada lugar,<br>uma nova leitura.</h2></div><span class="text-xs text-stone-500">2026 — PORTFÓLIO</span></div><Gallery :images="images" dark /><p class="mt-6 text-xs text-stone-500">Estudos ilustrativos com fotografias de referência. Não representam obras executadas pelo estúdio.</p></section>
    <section class="grid gap-10 px-6 py-16 md:grid-cols-[1fr_2fr] md:px-12 md:py-24"><div><p class="text-xs uppercase tracking-[0.18em] text-stone-500">03 / Do encontro à forma</p><h2 class="mt-5 font-heading text-3xl font-normal tracking-tight">Um processo<br>construído junto.</h2></div><ol class="space-y-0"><li v-for="(step, i) in [{ title: 'Escuta e contexto', text: 'Rotina, desejos e possibilidades do lugar.' }, { title: 'Conceito e estudo', text: 'As primeiras relações entre espaço, luz e matéria.' }, { title: 'Desenvolvimento', text: 'Definições, materiais e detalhamento do projeto.' }]" :key="step.title" class="grid grid-cols-[35px_1fr] gap-5 border-t border-stone-300 py-6"><span class="text-xs text-stone-400">0{{ i + 1 }}</span><div><h3 class="text-lg">{{ step.title }}</h3><p class="mt-2 text-base text-stone-500">{{ step.text }}</p></div></li></ol></section>
    <ArchitectureReading />
    <section id="contato" class="border-t border-stone-300 px-6 py-16 md:px-12"><p class="text-xs uppercase tracking-[0.18em] text-stone-500">Seu trabalho merece uma boa apresentação</p><a :href="campaignWhatsapp('um site de arquitetura como o ArchStudio')" target="_blank" rel="noopener noreferrer" class="mt-5 flex items-center justify-between gap-8 font-heading text-4xl tracking-tight transition-colors hover:text-stone-500 md:text-6xl">Vamos criar seu site.<span aria-hidden="true">↗</span></a><p class="mt-6 text-xs text-stone-500">Contato com a Avyro para criação de sites. Este é um estúdio demonstrativo.</p></section>
    <footer class="flex justify-between border-t border-stone-300 px-6 py-6 text-xs text-stone-500 md:px-12"><span>arch/studio — demonstração</span><NuxtLink to="/#portfolio">Avyro ↗</NuxtLink></footer>
  </div>
</template>
