<script setup lang="ts">
import ClimateChecklist from '~/components/campaign/ClimateChecklist.vue'
import DemoContact from '~/components/campaign/DemoContact.vue'
import { climateEnvironments } from '~/constants/sectorDemos'
definePageMeta({ layout: 'demonstracao' })
useDemoSeo('Brisa — climatização para o seu ambiente', 'Modelo de site para instalação e manutenção de ar-condicionado, com seleção de ambientes e preparação do atendimento.')
const { index, current, choose } = useDemoChoice(climateEnvironments)
</script>
<template>
  <div class="bg-[#f7fbfc] text-[#163946]">
    <header class="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5 px-6 py-7"><NuxtLink to="/exemplos/climatizacao" class="text-3xl font-semibold tracking-tight">brisa<span class="text-[#428e98]">°</span></NuxtLink><nav aria-label="Brisa" class="flex flex-wrap gap-6 text-sm"><a href="#ambientes">Seu ambiente</a><a href="#servicos">Nossos serviços</a><a href="#contato" class="font-semibold">Vamos conversar ↗</a></nav></header>
    <section class="mx-auto grid max-w-7xl gap-10 px-6 pb-16 pt-9 lg:grid-cols-[1.05fr_1fr] lg:items-center">
      <div><p class="text-sm uppercase tracking-[0.2em] text-[#428e98]">Climatização, do projeto ao cuidado.</p><h1 class="mt-7 text-5xl font-semibold leading-[1.08] tracking-[-0.055em] md:text-7xl">O clima muda.<br>Seu conforto<br><span class="text-[#428e98]">permanece.</span></h1><p class="mt-7 max-w-md text-lg leading-8 text-slate-500">Instalação e manutenção de ar-condicionado com atenção ao espaço, à rotina e a quem está nele.</p><a href="#ambientes" class="mt-8 inline-flex gap-8 rounded-full bg-[#163946] px-7 py-4 text-sm font-semibold text-white hover:bg-[#286071]">Encontrar meu tipo de projeto ↓</a></div>
      <div class="overflow-hidden rounded-t-[150px] rounded-b-3xl bg-[#dfecee]"><img src="/images/campaign/climate.jpg" alt="Ar-condicionado de parede em ambiente interno" width="1200" height="1400" fetchpriority="high" class="aspect-[4/5] w-full object-cover"><p class="px-7 py-5 text-sm">Um bom ambiente começa com um projeto bem pensado.</p></div>
    </section>
    <section id="ambientes" class="bg-[#e7f0f1] px-6 py-16 md:py-24"><div class="mx-auto max-w-6xl"><div class="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p class="text-sm uppercase tracking-widest text-[#428e98]">01 / Onde você precisa de conforto?</p><h2 class="mt-4 text-3xl font-semibold tracking-tight md:text-4xl">Cada ambiente pede uma conversa.</h2></div><div class="flex flex-wrap gap-2" role="group" aria-label="Tipo de ambiente"><button v-for="(item, i) in climateEnvironments" :key="item.name" :aria-pressed="index === i" class="rounded-full border border-[#b7cdd0] px-5 py-3 text-sm transition-colors" :class="index === i ? 'bg-[#163946] text-white' : 'bg-white hover:bg-[#d8e8ea]'" @click="choose(i)">{{ item.name }}</button></div></div>
      <div class="mt-10 grid overflow-hidden rounded-3xl bg-white md:grid-cols-2"><img :src="current.image" :alt="`Referência de ambiente: ${current.name}`" width="1000" height="800" loading="lazy" class="h-full min-h-72 w-full object-cover"><div class="p-8 md:p-12" aria-live="polite"><p class="text-sm text-[#428e98]">{{ current.name }}</p><h3 class="mt-4 text-3xl font-semibold leading-snug">{{ current.title }}</h3><p class="mt-5 text-base leading-8 text-slate-500">{{ current.text }}</p><p class="mt-7 text-sm font-semibold">O que vamos considerar</p><ul class="mt-4 space-y-3 text-base text-slate-600"><li v-for="item in current.items" :key="item">↗ {{ item }}</li></ul><p class="mt-7 text-sm leading-6 text-slate-400">Capacidade e equipamento são definidos após avaliação técnica do ambiente.</p></div></div>
    </div></section>
    <section id="servicos" class="mx-auto max-w-6xl px-6 py-20"><p class="text-sm uppercase tracking-widest text-[#428e98]">02 / Um ciclo completo de cuidado</p><div class="mt-9 grid gap-8 md:grid-cols-3"><article v-for="(service, i) in [{ title: 'Instalar com planejamento', text: 'Local das unidades, infraestrutura e acabamento entram no planejamento antes da instalação.' }, { title: 'Manter o cuidado em dia', text: 'Uma rotina de inspeção e manutenção considera o equipamento e as condições de uso.' }, { title: 'Entender antes de reparar', text: 'O diagnóstico identifica o problema e orienta a proposta de correção.' }]" :key="service.title" class="border-t border-[#c1d5d8] pt-6"><span class="text-4xl font-light text-[#a9c9cf]">0{{ i + 1 }}</span><h2 class="mt-6 text-2xl font-semibold">{{ service.title }}</h2><p class="mt-4 text-base leading-8 text-slate-500">{{ service.text }}</p></article></div></section>
    <section class="mx-6 mb-16 rounded-3xl bg-[#163946] px-8 py-12 text-white md:mx-auto md:max-w-6xl md:px-12"><div class="grid gap-8 md:grid-cols-2"><h2 class="text-3xl font-semibold leading-tight">O atendimento começa<br>com informação simples.</h2><div><p class="text-base leading-8 text-slate-300">Separe fotos do ambiente, informe o tipo de uso e conte se já existe um equipamento instalado. Esses detalhes ajudam a preparar a conversa.</p><details class="mt-6 border-t border-white/20 pt-5"><summary class="cursor-pointer text-base">Consigo definir tudo pelo site?</summary><p class="mt-4 text-base leading-7 text-slate-300">O site pode organizar o primeiro contato. O dimensionamento e a proposta dependem da avaliação do local.</p></details></div></div></section>
    <ClimateChecklist />
    <DemoContact name="Brisa Climatização" :subject="`um site para climatização como o Brisa, com seleção de ambiente: ${current.name}`" title="Seu próximo cliente pode chegar por um site assim." />
  </div>
</template>
