<script setup lang="ts">
import DemoNavigation from '~/components/campaign/DemoNavigation.vue'
import AccountingBoard from '~/components/campaign/AccountingBoard.vue'
import DemoContact from '~/components/campaign/DemoContact.vue'
import { businessStages } from '~/constants/sectorDemos'
definePageMeta({ layout: 'demonstracao' })
useDemoSeo('Nexo — contabilidade para o próximo passo', 'Modelo de site contábil com jornadas para abertura, migração e acompanhamento de empresas.')
const { index, current, choose } = useDemoChoice(businessStages)
</script>
<template>
  <div class="bg-[#f5f5ed] text-[#193e34]">
    <header class="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5 px-6 py-7"><NuxtLink to="/exemplos/contabilidade" class="text-4xl font-extrabold tracking-[-0.08em]">nexo<span class="text-[#7c992d]">.</span></NuxtLink><DemoNavigation dark><nav aria-label="Nexo" class="flex flex-wrap items-center gap-6 text-sm"><a href="#momento">Seu momento</a><a href="#rotina">Como trabalhamos</a><a href="#contato" class="rounded-full border border-[#193e34] px-5 py-3">Começar uma conversa ↗</a></nav></DemoNavigation></header>
    <section class="mx-auto max-w-7xl px-6 pb-16 pt-10"><div class="grid gap-10 lg:grid-cols-[1.15fr_0.85fr]"><div class="py-6"><p class="text-sm font-semibold uppercase tracking-[0.15em] text-[#7c992d]">Contabilidade que conversa com o negócio</p><h1 class="mt-6 text-5xl font-semibold leading-[1.04] tracking-[-0.06em] md:text-7xl">Menos dúvidas.<br>Mais clareza.<br><span class="text-[#7c992d]">Próximo passo.</span></h1><p class="mt-7 max-w-md text-lg leading-8 text-[#6e7d6e]">Da primeira ideia à rotina da empresa. Informação organizada para você conversar sobre o que vem pela frente.</p><a href="#momento" class="mt-8 inline-flex gap-8 rounded-full bg-[#ddec95] px-7 py-4 text-sm font-semibold hover:bg-[#d0e278]">Encontrar meu momento ↓</a></div>
      <div class="rounded-[32px] bg-[#193e34] p-7 text-white md:p-10"><div class="flex justify-between border-b border-white/20 pb-6 text-sm"><span>SEU NEGÓCIO / EM FOCO</span><span class="text-[#ddec95]">↗</span></div><p class="mt-9 text-sm text-[#b0c6b9]">Uma boa parceria conecta</p><h2 class="mt-4 text-4xl font-medium leading-tight">informação<br><span class="text-[#ddec95]">+ decisão.</span></h2><div class="mt-10 space-y-3"><div v-for="(item, i) in ['Entender a operação', 'Organizar a rotina', 'Acompanhar as entregas']" :key="item" class="flex items-center gap-4 rounded-xl bg-white/10 p-5"><span class="text-[#ddec95]">0{{ i + 1 }}</span><span class="text-base">{{ item }}</span></div></div><p class="mt-7 text-sm leading-6 text-[#b0c6b9]">Sem promessas prontas. O escopo começa pelo que a empresa precisa.</p></div></div></section>
    <section id="momento" class="bg-white px-6 py-20"><div class="mx-auto max-w-6xl"><p class="text-sm font-semibold uppercase tracking-widest text-[#7c992d]">Vamos por partes</p><h2 class="mt-4 text-4xl font-semibold tracking-tight">Em que momento você está?</h2><div class="mt-8 grid gap-3 md:grid-cols-3" role="group" aria-label="Momento da empresa"><button v-for="(stage, i) in businessStages" :key="stage.name" :aria-pressed="index === i" class="rounded-xl border p-5 text-left text-base font-semibold transition-colors" :class="index === i ? 'border-[#193e34] bg-[#193e34] text-white' : 'border-[#dce2d7] hover:bg-[#f5f5ed]'" @click="choose(i)">{{ stage.name }} <span aria-hidden="true">↗</span></button></div><div class="mt-6 grid overflow-hidden rounded-2xl border border-[#dce2d7] lg:grid-cols-2" aria-live="polite"><div class="p-8 md:p-10"><p class="text-sm font-semibold text-[#7c992d]">{{ current.label }}</p><h3 class="mt-5 text-3xl font-semibold leading-tight">{{ current.title }}</h3><p class="mt-5 text-base leading-8 text-[#6e7d6e]">{{ current.text }}</p><div class="mt-7 border-l-4 border-[#ddec95] pl-5 text-base leading-7">{{ current.delivery }}</div></div><div class="bg-[#f5f5ed] p-8 md:p-10"><p class="text-sm font-semibold uppercase tracking-widest">Prepare para a conversa</p><ul class="mt-6 space-y-0"><li v-for="(item, i) in current.checklist" :key="item" class="flex gap-4 border-b border-[#dce2d7] py-4 text-base"><span class="text-[#7c992d]">0{{ i + 1 }}</span>{{ item }}</li></ul><p class="mt-6 text-sm leading-6 text-[#6e7d6e]">Roteiro ilustrativo, sem envio de dados ou análise fiscal.</p></div></div></div></section>
    <section id="rotina" class="mx-auto max-w-6xl px-6 py-20"><div class="grid gap-12 md:grid-cols-[0.8fr_1.2fr]"><div><p class="text-sm text-[#7c992d]">UMA ROTINA COMBINADA</p><h2 class="mt-5 text-4xl font-semibold leading-tight tracking-tight">Você sabe o que<br>está acontecendo.</h2></div><div><article v-for="item in [{ title: 'Documentos com destino certo', text: 'Canais e responsáveis definidos para organizar a troca de informações.' }, { title: 'Entregas que você entende', text: 'Explicação sobre o que está sendo acompanhado e o que depende da empresa.' }, { title: 'Conversa quando precisa', text: 'Dúvidas organizadas para que o atendimento conheça o contexto do negócio.' }]" :key="item.title" class="border-t border-[#cbd6c9] py-6"><h3 class="text-xl font-semibold">{{ item.title }}</h3><p class="mt-3 text-base leading-8 text-[#6e7d6e]">{{ item.text }}</p></article></div></div></section>
    <AccountingBoard />
    <DemoContact name="Nexo Contabilidade" :subject="`um site contábil como o Nexo, com jornada: ${current.name}`" title="Seu escritório pode receber melhor desde o primeiro clique." />
  </div>
</template>
