<script setup lang="ts">
import DemoNavigation from '~/components/campaign/DemoNavigation.vue'
import EngineeringTimeline from '~/components/campaign/EngineeringTimeline.vue'
import DemoContact from '~/components/campaign/DemoContact.vue'
import { constructionStages } from '~/constants/sectorDemos'
definePageMeta({ layout: 'demonstracao' })
useDemoSeo('Prumo — engenharia e reformas', 'Modelo de site para engenharia com etapas de obra, escopo e acompanhamento de execução.')
const { index, current, choose } = useDemoChoice(constructionStages)
</script>
<template>
  <div class="bg-[#eeeee9] text-[#30362f]">
    <header class="flex flex-wrap items-center justify-between gap-6 border-b border-[#cbd0c6] px-6 py-7 md:px-12"><NuxtLink to="/exemplos/engenharia" class="text-3xl font-extrabold tracking-[-0.06em]">PRUMO<span class="ml-3 hidden sm:inline text-xs font-normal tracking-[0.18em]">ENGENHARIA</span></NuxtLink><DemoNavigation><nav aria-label="Prumo" class="flex flex-wrap gap-6 text-sm"><a href="#atuacao">Atuação</a><a href="#etapas">Método de trabalho</a><a href="#contato">Seu projeto ↗</a></nav></DemoNavigation></header>
    <section class="grid lg:grid-cols-[0.9fr_1.1fr]"><div class="flex flex-col justify-center px-6 py-16 md:px-12"><p class="text-sm font-semibold uppercase tracking-[0.16em] text-[#8a583f]">Engenharia / Execução / Gestão</p><h1 class="mt-7 text-5xl font-semibold leading-[1.06] tracking-[-0.05em] md:text-7xl">Uma boa obra<br>começa<br><span class="text-[#8a583f]">antes da obra.</span></h1><p class="mt-7 max-w-md text-lg leading-8 text-[#73796d]">Planejamento, acompanhamento e conversa clara. Do entendimento do imóvel à conferência da entrega.</p><a href="#etapas" class="mt-8 inline-flex items-center justify-between gap-8 self-start bg-[#30362f] px-6 py-4 text-sm font-semibold text-white hover:bg-[#505b4c]">Conheça nosso método ↓</a></div><div class="relative"><img src="/images/campaign/construction.jpg" alt="Canteiro de obras com estrutura e equipamentos de construção" width="1200" height="1300" fetchpriority="high" class="h-full min-h-96 w-full object-cover"><div class="absolute bottom-0 left-0 bg-[#d7e78f] p-6"><p class="text-sm font-semibold uppercase tracking-widest">Visão do todo.</p><p class="mt-2 text-base">Atenção a cada etapa.</p></div></div></section>
    <section id="atuacao" class="mx-auto max-w-7xl px-6 py-20 md:px-12"><div class="flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 class="text-4xl font-semibold tracking-tight">Espaços diferentes.<br>O mesmo rigor no processo.</h2><p class="max-w-sm text-base leading-7 text-[#73796d]">O escopo acompanha o imóvel, sua finalidade e o que precisa ser transformado.</p></div><div class="mt-10 grid gap-0 border-y border-[#cbd0c6] md:grid-cols-3"><article v-for="(item, i) in [{ title: 'Reformas residenciais', text: 'Ambientes que precisam acompanhar uma nova rotina. Planejamento das intervenções e organização da execução.' }, { title: 'Espaços comerciais', text: 'Obras pensadas em relação ao funcionamento do negócio, circulação e necessidades da operação.' }, { title: 'Gestão de execução', text: 'Coordenação das frentes de trabalho, registros de evolução e comunicação das decisões.' }]" :key="item.title" class="border-b border-[#cbd0c6] py-8 md:border-b-0 md:px-6"><p class="text-sm text-[#8a583f]">0{{ i + 1 }} / ATUAÇÃO</p><h3 class="mt-6 text-2xl font-semibold">{{ item.title }}</h3><p class="mt-5 text-base leading-8 text-[#73796d]">{{ item.text }}</p></article></div></section>
    <section id="etapas" class="bg-[#30362f] px-6 py-20 text-white md:px-12"><div class="mx-auto max-w-6xl"><p class="text-sm uppercase tracking-widest text-[#d7e78f]">Método de trabalho</p><h2 class="mt-5 text-4xl font-semibold tracking-tight md:text-5xl">Você acompanha o caminho.</h2><p class="mt-5 text-base leading-8 text-[#aeb6a8]">Explore as etapas e conheça as entregas de cada fase.</p><div class="mt-10 grid grid-cols-2 gap-3 md:grid-cols-4" role="group" aria-label="Etapas da obra"><button v-for="(stage, i) in constructionStages" :key="stage.name" :aria-pressed="index === i" class="border p-5 text-left transition-colors" :class="index === i ? 'border-[#d7e78f] bg-[#d7e78f] text-[#30362f]' : 'border-[#697360] hover:bg-white/10'" @click="choose(i)"><span class="mb-5 block text-sm opacity-70">0{{ i + 1 }}</span><span class="text-base font-semibold">{{ stage.name }}</span></button></div><div class="mt-6 grid gap-10 border border-[#697360] p-8 md:grid-cols-2 md:p-12" aria-live="polite"><div><p class="text-sm tracking-widest text-[#d7e78f]">{{ current.tag }}</p><h3 class="mt-5 text-3xl font-semibold leading-tight">{{ current.title }}</h3><p class="mt-6 text-base leading-8 text-[#aeb6a8]">{{ current.text }}</p></div><div><p class="text-sm uppercase tracking-widest text-[#aeb6a8]">Entregas da etapa</p><ul class="mt-5"><li v-for="item in current.deliverables" :key="item" class="border-b border-[#697360] py-4 text-base">↗ {{ item }}</li></ul></div></div></div></section>
    <section class="mx-auto grid max-w-6xl gap-12 px-6 py-20 md:grid-cols-2"><h2 class="text-4xl font-semibold leading-tight tracking-tight">Antes de começar,<br>vamos alinhar.</h2><div><details v-for="item in [{ question: 'O que preciso levar para a primeira conversa?', answer: 'Fotos do imóvel, plantas disponíveis e uma descrição do que você gostaria de transformar ajudam no levantamento inicial.' }, { question: 'O site informa prazo e valor da obra?', answer: 'O escopo, as condições do imóvel e a sequência de serviços orientam a proposta. Cada projeto precisa de uma avaliação própria.' }, { question: 'Este acompanhamento mostra uma obra real?', answer: 'Não. As etapas demonstram a apresentação de um método de trabalho. Prumo é uma empresa fictícia e não existe uma obra em execução neste site.' }]" :key="item.question" class="border-b border-[#cbd0c6] py-5"><summary class="cursor-pointer text-base font-semibold">{{ item.question }}</summary><p class="mt-4 text-base leading-8 text-[#73796d]">{{ item.answer }}</p></details></div></section>
    <EngineeringTimeline />
    <DemoContact name="Prumo Engenharia" subject="um site para engenharia e reformas como o Prumo, com apresentação das etapas de obra" title="Mostre a organização por trás de cada entrega." />
  </div>
</template>
