<script setup lang="ts">
import FlowerGift from '~/components/advanced/FlowerGift.vue'
import DemoNavigation from '~/components/campaign/DemoNavigation.vue'
import FlowerDetails from '~/components/florist/FlowerDetails.vue'
import { floralOccasions, floralCategories } from '~/constants/florist'
import type { FloralProduct } from '~/types/florist'
import { campaignWhatsapp } from '~/utils/campaign'
definePageMeta({ layout: 'demonstracao' })
useDemoSeo('Afeto Flores — um gesto que floresce', 'Modelo de floricultura com catálogo por ocasião, busca de flores, seleção de presentes e cartão personalizado.')
const { query, category, occasion, savedIds, onlySaved, note, visible, saved, toggle, reset } = useFloralCatalog()
const selected = ref<FloralProduct | null>(null)
const details = ref<InstanceType<typeof FlowerDetails> | null>(null)
function show(product: FloralProduct) { selected.value = product; details.value?.open() }
</script>

<template>
  <div class="bg-[#fffaf5] text-[#552338]">
    <div class="bg-[#f7e5e7] px-5 py-2 text-center text-xs tracking-wide">Para grandes datas. Para pequenos gestos. Para estar perto.</div>
    <header class="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-6 md:px-8">
      <NuxtLink to="/exemplos/floricultura" class="font-['Playfair_Display'] text-3xl tracking-tight sm:text-4xl">afeto<span class="ml-2 text-xl">✳</span><span class="mt-1 block font-body text-[10px] uppercase tracking-[0.4em]">flores & encontros</span></NuxtLink>
      <DemoNavigation><nav aria-label="Afeto Flores" class="flex gap-7 text-sm"><a href="#catalogo">Nossas flores</a><a href="#gesto">Seu presente</a><a href="#cuidados">Feito com carinho</a><a href="#contato">Vamos conversar ↗</a></nav></DemoNavigation>
    </header>
    <section class="mx-3 grid overflow-hidden rounded-[24px] bg-[#f4ddd9] sm:mx-6 lg:grid-cols-2">
      <div class="flex flex-col items-start justify-center px-6 py-12 sm:px-12 lg:px-16 lg:py-20"><p class="text-xs uppercase tracking-[0.22em]">Um gesto muda o dia.</p><h1 class="mt-6 font-['Playfair_Display'] text-5xl leading-[1.08] tracking-tight sm:text-6xl lg:text-7xl">Tem coisas que<br>só as <em>flores</em><br>sabem dizer.</h1><p class="mt-6 max-w-sm text-base leading-7 text-[#805464]">Para celebrar, agradecer ou lembrar alguém de que você está por perto. Encontre o seu jeito de dizer.</p><a href="#catalogo" class="mt-8 inline-flex min-h-12 items-center gap-6 rounded-full bg-[#792d49] px-7 py-4 text-sm font-semibold text-white">Encontre suas flores <span aria-hidden="true">↗</span></a><p class="mt-5 text-xs">Buquês cheios de cor. Histórias cheias de afeto.</p></div>
      <div class="relative"><img src="/images/campaign/flowers-bouquet.jpg" alt="Buquê delicado de flores em tons rosados e folhagens" width="1200" height="1400" fetchpriority="high" class="aspect-[4/3] h-full w-full object-cover lg:aspect-[4/5]"><span class="absolute bottom-5 right-5 flex h-24 w-24 rotate-12 items-center justify-center rounded-full bg-[#fffaf5] p-3 text-center font-['Playfair_Display'] text-lg italic">Um pouco<br>de carinho.</span></div>
    </section>
    <section id="catalogo" class="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:py-24">
      <div class="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p class="text-xs uppercase tracking-[0.2em]">Flores para o que você sente</p><h2 class="mt-3 font-['Playfair_Display'] text-4xl sm:text-5xl">Qual é a ocasião?</h2></div><a href="#gesto" class="inline-flex min-h-11 items-center self-start rounded-full border border-[#dcc0c9] px-5 text-sm">Minha seleção <span class="ml-3" aria-live="polite">{{ saved.length }}</span></a></div>
      <div class="mt-8 flex flex-wrap gap-2" role="group" aria-label="Filtrar por ocasião"><button v-for="item in floralOccasions" :key="item" :aria-pressed="occasion === item" class="min-h-11 rounded-full border border-[#dcc0c9] px-4 py-3 text-sm" :class="occasion === item ? 'bg-[#792d49] text-white' : 'hover:bg-[#f7e5e7]'" @click="occasion = item">{{ item }}</button></div>
      <div class="mt-6 grid gap-3 sm:grid-cols-[1fr_190px]"><label class="block text-sm"><span class="mb-2 block">Buscar no jardim</span><input v-model="query" type="search" placeholder="Tulipas, girassóis, tons de rosa…" class="min-h-12 w-full rounded-lg border border-[#dcc0c9] bg-white px-4"></label><label class="block text-sm"><span class="mb-2 block">Tipo de composição</span><select v-model="category" class="min-h-12 w-full rounded-lg border border-[#dcc0c9] bg-white px-3"><option v-for="item in floralCategories" :key="item">{{ item }}</option></select></label></div>
      <div class="my-5 flex flex-wrap items-center justify-between gap-3 text-sm"><p role="status">{{ visible.length }} composições encontradas</p><label class="flex min-h-11 items-center gap-2"><input v-model="onlySaved" type="checkbox" class="h-5 w-5 accent-[#792d49]">Só minha seleção</label></div>
      <div v-if="visible.length" class="grid grid-cols-2 gap-x-3 gap-y-8 sm:gap-6 lg:grid-cols-3">
        <article v-for="product in visible" :key="product.id" class="group"><button class="relative block w-full overflow-hidden rounded-xl bg-[#eee2dc] text-left" :aria-label="`Conhecer ${product.name}`" @click="show(product)"><img :src="product.image" :alt="product.alt" width="600" height="700" loading="lazy" class="aspect-[4/5] w-full object-cover transition-transform duration-500 group-hover:scale-105"><span class="absolute bottom-3 right-3 flex h-11 w-11 items-center justify-center rounded-full bg-white text-xl" aria-hidden="true">↗</span></button><p class="mt-4 text-[11px] uppercase tracking-widest text-[#926476]">{{ product.category }}</p><h3 class="mt-1 font-['Playfair_Display'] text-xl sm:text-2xl">{{ product.name }}</h3><p class="mt-2 text-xs leading-5 text-[#926476] sm:text-sm">{{ product.palette }}</p><button :aria-pressed="savedIds.includes(product.id)" class="mt-3 min-h-11 border-b border-[#c99ba9] text-left text-xs sm:text-sm" @click="toggle(product.id)">{{ savedIds.includes(product.id) ? '✓ Na sua seleção · remover' : '+ Guardar este carinho' }}</button></article>
      </div>
      <div v-else class="rounded-xl border border-dashed border-[#dcc0c9] p-8 text-center"><h3 class="font-['Playfair_Display'] text-2xl">Vamos tentar outra combinação?</h3><p class="mt-3 text-sm">Nenhuma flor corresponde aos filtros escolhidos.</p><button class="mt-5 min-h-11 rounded-full bg-[#792d49] px-6 text-sm text-white" @click="reset">Ver todas as flores</button></div>
      <p class="mt-8 text-xs leading-5 text-[#926476]">Catálogo ilustrativo, sem vendas ou entregas. Fotografias de referência: Unsplash.</p>
    </section>
    <FlowerGift />
    <section id="gesto" class="bg-[#f7e5e7] px-5 py-16 sm:px-8"><div class="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2">
      <div><p class="text-xs uppercase tracking-[0.2em]">O detalhe que só você pode dar</p><h2 class="mt-4 font-['Playfair_Display'] text-4xl sm:text-5xl">Flores levam cor.<br><em>Suas palavras, sentido.</em></h2><p class="mt-5 max-w-md text-base leading-7 text-[#805464]">Guarde suas composições favoritas e experimente uma mensagem para acompanhar o presente.</p><label for="flower-note" class="mb-2 mt-6 block text-sm font-semibold">O que você gostaria de dizer?</label><textarea id="flower-note" v-model="note" maxlength="180" rows="3" placeholder="Vi estas flores e lembrei de você…" class="w-full rounded-xl border border-[#d6afb8] bg-[#fffaf5] p-4 text-base" /><p class="mt-2 text-right text-xs">{{ note.length }}/180</p></div>
      <div class="flex flex-col justify-center"><div class="rotate-[-1deg] bg-[#fffdf8] p-7 shadow-sm sm:p-10"><p class="text-xs uppercase tracking-[0.25em] text-[#926476]">Um cartão. Muito afeto.</p><p class="my-8 whitespace-pre-wrap break-words font-['Playfair_Display'] text-2xl italic leading-relaxed">{{ note || 'Vi estas flores e lembrei de você…' }}</p><p class="font-['Playfair_Display'] text-xl">com afeto ✳</p></div><div class="mt-7"><p class="text-sm font-semibold" aria-live="polite">Sua seleção · {{ saved.length }} {{ saved.length === 1 ? 'composição' : 'composições' }}</p><ul v-if="saved.length" class="mt-3 divide-y divide-[#d6afb8]"><li v-for="product in saved" :key="product.id" class="flex items-center justify-between gap-3 py-2 text-sm"><span>{{ product.name }}</span><button class="min-h-11 px-2 underline" :aria-label="`Remover ${product.name}`" @click="toggle(product.id)">Remover</button></li></ul><p v-else class="mt-3 text-sm text-[#805464]">Escolha uma flor no catálogo para começar.</p><p class="mt-4 text-xs leading-5 text-[#805464]">Demonstração local: a seleção e o cartão não são enviados nem salvos após sair da página.</p></div></div>
    </div></section>
    <section id="cuidados" class="mx-auto max-w-6xl px-5 py-16 sm:px-8"><p class="text-xs uppercase tracking-widest">Do primeiro olhar ao último detalhe</p><div class="mt-8 grid gap-8 md:grid-cols-3"><div><span class="font-['Playfair_Display'] text-4xl italic">01.</span><h2 class="mt-4 text-xl">Escolha pelo sentimento</h2><p class="mt-3 text-sm leading-7 text-[#805464]">A ocasião é o começo. Cores e texturas ajudam você a encontrar uma composição com a cara de quem vai receber.</p></div><div><span class="font-['Playfair_Display'] text-4xl italic">02.</span><h2 class="mt-4 text-xl">Deixe sua marca</h2><p class="mt-3 text-sm leading-7 text-[#805464]">Uma mensagem curta pode dizer muito. Experimente o cartão e veja seu presente ganhar personalidade.</p></div><div><span class="font-['Playfair_Display'] text-4xl italic">03.</span><h2 class="mt-4 text-xl">Continue o cuidado</h2><p class="mt-3 text-sm leading-7 text-[#805464]">Água limpa, um lugar fresco e atenção às flores. Pequenos cuidados fazem parte do gesto.</p></div></div></section>
    <footer id="contato" class="bg-[#552338] px-5 py-14 text-[#fffaf5] sm:px-8"><div class="mx-auto max-w-6xl"><p class="font-['Playfair_Display'] text-3xl">Seu negócio também pode florescer.</p><p class="mt-4 max-w-xl text-sm leading-7 text-[#dfbcc9]">Afeto Flores é um modelo fictício da Avyro. Tenha um site com catálogo, sua identidade e manutenção mensal opcional.</p><a :href="campaignWhatsapp('um site de floricultura como o Afeto Flores, com catálogo e seleção de presentes')" target="_blank" rel="noopener noreferrer" class="mt-7 inline-flex min-h-12 items-center rounded-full bg-[#fffaf5] px-6 py-3 text-sm font-semibold text-[#552338]">Quero uma floricultura assim ↗</a></div></footer>
    <FlowerDetails ref="details" :product="selected" :saved="!!selected && savedIds.includes(selected.id)" @toggle="toggle" />
  </div>
</template>
