<script setup lang="ts">
import FloralMoodboard from '~/components/advanced/FloralMoodboard.vue'
import DemoNavigation from '~/components/campaign/DemoNavigation.vue'
import FlowerDetails from '~/components/florist/FlowerDetails.vue'
import { floralCategories, floralRhythms } from '~/constants/florist'
import type { FloralProduct } from '~/types/florist'
import { campaignWhatsapp } from '~/utils/campaign'
definePageMeta({ layout: 'demonstracao' })
useDemoSeo('Casa Flora — natureza para habitar', 'Modelo de ateliê floral com catálogo editorial, seleção de composições e experiência de flores recorrentes para espaços.')
const { query, category, savedIds, onlySaved, visible, saved, toggle, reset } = useFloralCatalog()
const { index, current, choose } = useDemoChoice(floralRhythms)
const selected = ref<FloralProduct | null>(null)
const details = ref<InstanceType<typeof FlowerDetails> | null>(null)
function show(product: FloralProduct) { selected.value = product; details.value?.open() }
</script>

<template>
  <div class="bg-[#eeeee5] text-[#343e31]">
    <header class="mx-auto flex max-w-[1440px] items-center justify-between gap-4 border-b border-[#c6cbb9] px-5 py-6 md:px-10"><NuxtLink to="/exemplos/floricultura-atelie" class="font-['Playfair_Display'] text-2xl uppercase tracking-[0.08em] sm:text-3xl">Casa Flora<span class="mt-1 block font-body text-[9px] tracking-[0.3em]">Ateliê botânico</span></NuxtLink><DemoNavigation><nav aria-label="Casa Flora" class="flex gap-8 text-xs uppercase tracking-widest"><a href="#colecao">Coleção</a><a href="#ritmo">Flores na rotina</a><a href="#atelie">O ateliê</a><a href="#contato">Seu projeto ↗</a></nav></DemoNavigation></header>
    <section class="mx-auto max-w-[1440px] px-5 pb-12 pt-10 md:px-10 md:pt-16"><div class="flex flex-col justify-between gap-6 pb-10 lg:flex-row lg:items-end"><h1 class="font-['Playfair_Display'] text-5xl leading-[1.04] tracking-[-0.045em] sm:text-7xl lg:text-[88px]">A natureza tem<br>um jeito de <em>ficar.</em></h1><p class="max-w-xs text-sm leading-7 text-[#6a745f]">Flores, matéria e tempo.<br>Composições para transformar espaços<br>em lugares de estar.</p></div><div class="grid gap-4 md:grid-cols-[1.5fr_1fr]"><div class="relative"><img src="/images/campaign/flowers-window.jpg" alt="Composição floral recebendo luz natural junto à janela" width="1400" height="1000" fetchpriority="high" class="aspect-[4/3] h-full w-full object-cover"><a href="#colecao" class="absolute bottom-4 left-4 inline-flex min-h-12 items-center gap-8 bg-[#eeeee5] px-5 py-3 text-sm">Entrar no jardim <span aria-hidden="true">↗</span></a></div><div class="grid grid-cols-2 gap-4 md:grid-cols-1"><img src="/images/campaign/flowers-tulips.jpg" alt="Tulipas brancas e vaso azul em uma composição de linhas simples" width="800" height="850" class="aspect-square h-full max-h-[460px] w-full object-cover"><p class="self-end py-3 text-xs leading-6 tracking-wide text-[#6a745f]">Caderno botânico / 01<br>Um estudo sobre presença.<br>O natural, sem pressa.</p></div></div></section>
    <section id="colecao" class="border-y border-[#c6cbb9] px-5 py-14 md:px-10 md:py-20"><div class="mx-auto max-w-[1360px] lg:grid lg:grid-cols-[230px_1fr] lg:gap-14">
      <aside class="self-start lg:sticky lg:top-8"><p class="text-xs uppercase tracking-[0.2em]">O catálogo do ateliê</p><h2 class="mt-4 font-['Playfair_Display'] text-4xl">Formas<br>de habitar.</h2><p class="mt-5 text-sm leading-7 text-[#6a745f]">Explore a coleção. Guarde as composições que conversam com o seu espaço.</p><label class="mb-2 mt-6 block text-xs uppercase tracking-widest" for="atelier-search">Buscar composição</label><input id="atelier-search" v-model="query" type="search" placeholder="Cor, flor ou nome" class="min-h-12 w-full border-b border-[#8d9980] bg-transparent text-base"><div class="mt-5 flex flex-wrap gap-2 lg:flex-col" role="group" aria-label="Coleções"><button v-for="item in floralCategories" :key="item" :aria-pressed="category === item" class="min-h-11 border-b px-3 py-3 text-left text-sm lg:px-0" :class="category === item ? 'border-[#343e31] font-semibold' : 'border-transparent text-[#6a745f]'" @click="category = item">{{ item }} <span v-if="category === item" aria-hidden="true">↗</span></button></div><label class="mt-5 flex min-h-11 items-center gap-2 text-sm"><input v-model="onlySaved" type="checkbox" class="h-5 w-5 accent-[#343e31]">Apenas guardadas</label><p class="mt-4 text-xs" role="status">{{ visible.length }} composições · {{ saved.length }} guardadas</p></aside>
      <div class="mt-10 lg:mt-0"><div v-if="visible.length" class="grid gap-x-7 gap-y-12 sm:grid-cols-2"><article v-for="(product, i) in visible" :key="product.id" :class="i % 2 ? 'sm:mt-16' : ''"><button class="group block w-full text-left" :aria-label="`Explorar ${product.name}`" @click="show(product)"><div class="overflow-hidden bg-[#d9ddcf]" :class="i % 3 === 0 ? 'rounded-t-[45%]' : ''"><img :src="product.image" :alt="product.alt" width="750" height="950" loading="lazy" class="aspect-[4/5] w-full object-cover transition-transform duration-700 group-hover:scale-105"></div><div class="mt-4 flex items-start justify-between gap-3 border-t border-[#c6cbb9] pt-4"><div><p class="text-[10px] uppercase tracking-widest text-[#6a745f]">Estudo {{ String(i + 1).padStart(2, '0') }} / {{ product.category }}</p><h3 class="mt-2 font-['Playfair_Display'] text-3xl">{{ product.name }}</h3></div><span class="text-2xl" aria-hidden="true">↗</span></div></button><p class="mt-3 max-w-sm text-sm leading-7 text-[#6a745f]">{{ product.description }}</p><button :aria-pressed="savedIds.includes(product.id)" class="mt-4 min-h-11 border-b border-[#8d9980] text-sm" @click="toggle(product.id)">{{ savedIds.includes(product.id) ? 'Guardada · remover −' : 'Guardar composição +' }}</button></article></div><div v-else class="border border-dashed border-[#a9b299] p-10 text-center"><h3 class="font-['Playfair_Display'] text-3xl">Um novo olhar?</h3><p class="mt-4 text-sm">Não encontramos composições com estes filtros.</p><button class="mt-6 min-h-11 border-b border-current px-3 text-sm" @click="reset">Reabrir a coleção ↗</button></div></div>
    </div></section>
    <FloralMoodboard />
    <section id="ritmo" class="bg-[#343e31] px-5 py-16 text-[#eeeee5] md:px-10 md:py-24"><div class="mx-auto grid max-w-6xl gap-12 lg:grid-cols-2"><div><p class="text-xs uppercase tracking-[0.2em] text-[#b8c1a7]">Flores como parte da vida</p><h2 class="mt-5 font-['Playfair_Display'] text-4xl leading-tight sm:text-5xl">Um jardim novo.<br>No seu <em>ritmo.</em></h2><p class="mt-6 max-w-md text-base leading-8 text-[#b8c1a7]">Na mesa de casa, na recepção ou no espaço de trabalho. Imagine uma curadoria de flores que acompanha a sua rotina.</p><p class="mt-6 text-xs leading-6 text-[#b8c1a7]">Experimente a frequência abaixo. Esta é uma simulação, sem assinatura ou cobrança.</p></div><div><div class="grid gap-2 sm:grid-cols-3" role="group" aria-label="Frequência das composições"><button v-for="(rhythm, i) in floralRhythms" :key="rhythm.name" :aria-pressed="index === i" class="min-h-14 border px-4 py-4 text-sm" :class="index === i ? 'border-[#d9e4bb] bg-[#d9e4bb] text-[#343e31]' : 'border-[#73816a] hover:bg-white/10'" @click="choose(i)">{{ rhythm.name }}</button></div><div class="mt-5 border border-[#73816a] p-6 sm:p-8" aria-live="polite"><p class="text-xs uppercase tracking-widest text-[#b8c1a7]">Seu ritmo botânico</p><h3 class="mt-5 font-['Playfair_Display'] text-3xl">{{ current.description }}</h3><p class="mt-5 text-sm leading-7 text-[#b8c1a7]">{{ current.visits }}</p><div class="my-6 flex gap-3" aria-hidden="true"><span v-for="n in (index === 0 ? 4 : index === 1 ? 2 : 1)" :key="n" class="flex h-14 w-14 items-center justify-center rounded-full border border-[#b8c1a7] text-2xl">✳</span></div><p class="border-t border-[#73816a] pt-5 text-sm">{{ saved.length ? `Sua curadoria: ${saved.map(p => p.name).join(', ')}.` : 'Guarde composições no catálogo para montar sua curadoria.' }}</p></div></div></div></section>
    <section id="atelie" class="mx-auto grid max-w-6xl gap-10 px-5 py-16 md:grid-cols-2 md:px-10 md:py-24"><img src="/images/campaign/flowers-white.jpg" alt="Flores brancas em composição delicada sobre madeira" width="900" height="1100" loading="lazy" class="aspect-[4/5] w-full object-cover"><div class="self-center"><p class="text-xs uppercase tracking-[0.2em] text-[#6a745f]">A matéria encontra o olhar</p><h2 class="mt-5 font-['Playfair_Display'] text-4xl leading-tight">Menos excesso.<br>Mais <em>presença.</em></h2><p class="mt-6 text-base leading-8 text-[#6a745f]">Cada haste tem seu movimento. Cada espaço, sua luz. O ponto de partida é observar — e deixar que as flores façam parte do lugar, naturalmente.</p><details class="mt-8 border-t border-[#a9b299] py-4"><summary class="flex cursor-pointer items-center justify-between gap-4 text-sm">Flores para espaços de trabalho <span aria-hidden="true">+</span></summary><p class="mt-4 text-sm leading-7 text-[#6a745f]">Uma proposta floral pode considerar a recepção, as salas e os encontros da empresa. Volume, paleta e frequência fazem parte da composição.</p></details><details class="border-y border-[#a9b299] py-4"><summary class="flex cursor-pointer items-center justify-between gap-4 text-sm">O cuidado também é parte do desenho <span aria-hidden="true">+</span></summary><p class="mt-4 text-sm leading-7 text-[#6a745f]">Um recipiente limpo, água renovada e distância do calor direto ajudam a cuidar das flores. Consulte os detalhes de cada composição no catálogo.</p></details></div></section>
    <footer id="contato" class="border-t border-[#a9b299] px-5 py-14 md:px-10"><div class="mx-auto flex max-w-6xl flex-col justify-between gap-8 md:flex-row md:items-end"><div><p class="text-xs uppercase tracking-widest">Casa Flora / Modelo Avyro</p><h2 class="mt-5 font-['Playfair_Display'] text-3xl">Um site com o olhar<br>do seu ateliê.</h2><p class="mt-4 max-w-md text-xs leading-6 text-[#6a745f]">Marca fictícia, catálogo ilustrativo e fotografias de referência do Unsplash. Converse com a Avyro sobre seu site, catálogo e manutenção opcional.</p></div><a :href="campaignWhatsapp('um site de ateliê floral como o Casa Flora, com catálogo e apresentação de flores recorrentes')" target="_blank" rel="noopener noreferrer" class="inline-flex min-h-12 items-center justify-center border-b border-current py-4 text-sm">Criar um site para meu ateliê ↗</a></div></footer>
    <FlowerDetails ref="details" :product="selected" :saved="!!selected && savedIds.includes(selected.id)" @toggle="toggle" />
  </div>
</template>
