<script setup lang="ts">
import PhotoEssay from '~/components/advanced/PhotoEssay.vue'
import PhotoHero from '~/components/photography/PhotoHero.vue'
import Portfolio from '~/components/photography/Portfolio.vue'
import { campaignWhatsapp } from '~/utils/campaign'
definePageMeta({ layout: 'demonstracao' })
useDemoSeo('Lume — fotografia para o que permanece', 'Landing page demonstrativa para fotógrafos com coleções, galeria editorial, visualização ampliada e seleção de referências.')
</script>
<template>
  <div class="bg-[#191915] text-[#e9e6df]">
    <PhotoHero />
    <section id="olhar" class="mx-auto grid max-w-[1440px] gap-12 px-6 py-20 md:grid-cols-[0.6fr_1.4fr] md:px-12 md:py-28"><p class="text-sm uppercase tracking-[0.2em] text-[#aa9b85]">Lume / Um jeito de olhar</p><div><h2 class="max-w-4xl font-['Playfair_Display'] text-3xl leading-[1.35] md:text-5xl">Há coisas que não pedem uma pose.<br><span class="text-[#aa9b85]">Pedem presença.</span></h2><div class="mt-10 grid gap-8 text-base leading-8 text-[#aa9b85] md:grid-cols-2"><p>Um encontro, uma pausa, uma mudança de luz. A fotografia começa na atenção ao que já está acontecendo.</p><p>O que queremos guardar nem sempre cabe em palavras. Às vezes, cabe em uma imagem que faz a gente voltar.</p></div></div></section>
    <PhotoEssay />
    <Portfolio />
    <section id="ensaio-visual" class="overflow-hidden px-6 py-20 md:px-12 md:py-28"><div class="mx-auto max-w-[1440px]"><div class="mb-12 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p class="text-sm uppercase tracking-[0.2em] text-[#aa9b85]">02 / Ensaio visual</p><h2 class="mt-5 font-['Playfair_Display'] text-4xl md:text-6xl">O tempo entre<br><em>um instante e outro.</em></h2></div><p class="max-w-sm text-base leading-8 text-[#aa9b85]">Uma pequena sequência para olhar devagar. A distância de uma paisagem. A proximidade de um encontro.</p></div><div class="grid items-center gap-7 md:grid-cols-[0.7fr_1.3fr]"><figure><img src="/images/campaign/photo-couple.jpg" alt="Casal durante a luz dourada, fotografia de Anna Vi" width="1000" height="1200" loading="lazy" class="aspect-[4/5] w-full object-cover"><figcaption class="mt-4 text-sm text-[#aa9b85]">I. Proximidade · Foto de Anna Vi</figcaption></figure><figure class="md:pl-12"><img src="/images/campaign/photo-mountain.jpg" alt="Paisagem de montanhas na Islândia, fotografia de Simon Peel" width="1400" height="900" loading="lazy" class="aspect-[1.5] w-full object-cover"><figcaption class="mt-4 text-sm text-[#aa9b85]">II. Distância · Foto de Simon Peel</figcaption><p class="mt-12 max-w-md font-['Playfair_Display'] text-3xl italic leading-snug text-[#cbbba2]">O mesmo mundo.<br>Tantas maneiras de sentir.</p></figure></div><p class="mt-10 text-sm text-[#aa9b85]">Curadoria ilustrativa com fotografias de autores diferentes; não representa um ensaio realizado pelo Lume.</p></div></section>
    <section id="experiencia" class="bg-[#a4432d] px-6 py-20 text-[#f5e9db] md:px-12"><div class="mx-auto grid max-w-6xl gap-12 md:grid-cols-[0.85fr_1.15fr]"><div><p class="text-sm uppercase tracking-[0.2em] text-[#e0b6a3]">03 / Da conversa à memória</p><h2 class="mt-6 font-['Playfair_Display'] text-4xl leading-tight md:text-5xl">Uma experiência<br>que começa<br><em>com você.</em></h2><p class="mt-7 max-w-sm text-base leading-8 text-[#e0b6a3]">Antes de definir cenário, roteiro ou formato, existe uma história para conhecer.</p></div><div><article v-for="(step, i) in [{ title: 'A conversa', text: 'O que você quer registrar, onde essas imagens vão viver e o que elas precisam transmitir.' }, { title: 'O encontro', text: 'Luz, local e ritmo pensados em relação à história. Espaço para direção e espontaneidade.' }, { title: 'A edição', text: 'Uma seleção cuidadosa para construir uma narrativa, do primeiro quadro ao último.' }]" :key="step.title" class="grid grid-cols-[40px_1fr] gap-5 border-t border-[#d3836b] py-7"><span class="text-sm text-[#e0b6a3]">0{{ i + 1 }}</span><div><h3 class="font-['Playfair_Display'] text-3xl">{{ step.title }}</h3><p class="mt-4 text-base leading-8 text-[#f1cfbf]">{{ step.text }}</p></div></article></div></div></section>
    <section id="contato" class="mx-auto max-w-[1440px] px-6 py-20 md:px-12 md:py-28"><p class="text-sm uppercase tracking-[0.2em] text-[#aa9b85]">O próximo olhar pode ser o seu</p><h2 class="mt-7 max-w-4xl font-['Playfair_Display'] text-5xl leading-[1.12] md:text-7xl">Seu trabalho merece<br><em>esse espaço.</em></h2><div class="mt-10 flex flex-col justify-between gap-8 md:flex-row md:items-end"><p class="max-w-lg text-base leading-8 text-[#aa9b85]">Converse com a Avyro sobre um site para seu portfólio, com galerias, coleções e manutenção mensal opcional.</p><a :href="campaignWhatsapp('um site avançado para fotografia como o Lume, com coleções, galeria ampliada e seleção de imagens')" target="_blank" rel="noopener noreferrer" class="inline-flex items-center justify-between gap-10 self-start rounded-full border border-[#aa9b85] px-8 py-5 text-base transition-colors hover:bg-[#e9e6df] hover:text-[#191915]">Criar meu site com a Avyro ↗</a></div></section>
    <footer class="flex flex-col justify-between gap-5 border-t border-[#49453e] px-6 py-7 text-sm text-[#aa9b85] md:flex-row md:px-12"><span>LUME · Estúdio fictício / demonstração Avyro</span><NuxtLink to="/modelos-site" class="underline underline-offset-4">Todos os modelos ↗</NuxtLink></footer>
  </div>
</template>
