<script setup lang="ts">
import DemoNavigation from '~/components/campaign/DemoNavigation.vue'
import NailsEditorial from '~/components/campaign/NailsEditorial.vue'
import Gallery from '~/components/campaign/Gallery.vue'
import { campaignWhatsapp } from '~/utils/campaign'
import type { GalleryImage } from '~/types/campaign'
definePageMeta({ layout: 'demonstracao' })
useDemoSeo('BellaNails — seu momento de cuidado', 'Demonstração de um site para estúdio de manicure: serviços, inspiração e atendimento.')
const services = [
  { name: 'Manicure essencial', detail: 'Cuidado das unhas, preparação e esmaltação para dar um toque de cor à rotina.', tag: 'O clássico, bem feito' },
  { name: 'Esmaltação em gel', detail: 'Preparação cuidadosa e acabamento em gel. Um encontro entre brilho, cor e delicadeza.', tag: 'Brilho em cada detalhe' },
  { name: 'Nail art', detail: 'Traços, cores e combinações escolhidos com você. Uma pequena expressão do seu estilo.', tag: 'Do seu jeito' },
  { name: 'Spa dos pés', detail: 'Uma pausa dedicada ao conforto dos pés, com cuidado e finalização.', tag: 'Uma pausa só sua' },
]
const selected = ref<number>(0)
const gallery: GalleryImage[] = [
  { src: '/images/campaign/nails-1.jpg', alt: 'Detalhe de esmaltação e cuidado das unhas', caption: '01 / Delicadeza nos detalhes' },
  { src: '/images/campaign/nails-2.jpg', alt: 'Inspiração de cores para manicure', caption: '02 / Sua cor, seu momento' },
  { src: '/images/campaign/nails-3.jpg', alt: 'Unhas com acabamento de manicure', caption: '03 / Um toque de personalidade' },
]
const contact = computed<string>(() => campaignWhatsapp(`um site de manicure como o BellaNails, com seleção de serviço (${services[selected.value]?.name})`))
</script>

<template>
  <div class="bg-[#fffaf7] text-[#4e2530]">
    <header class="mx-auto flex max-w-6xl items-center justify-between gap-5 px-6 py-7"><NuxtLink to="/exemplos/manicure" class="font-['Playfair_Display'] text-3xl">bella<span class="italic">nails</span><span class="ml-2 text-lg">✳</span></NuxtLink><DemoNavigation><nav class="flex gap-7 text-xs" aria-label="BellaNails"><a href="#cuidados" class="hover:underline">Nossos cuidados</a><a href="#inspiracao" class="hover:underline">Inspire-se</a><a href="#duvidas" class="hover:underline">Dúvidas</a></nav></DemoNavigation><a href="#conversa" class="hidden lg:inline-flex rounded-full border border-[#b78993] px-4 py-2.5 text-xs">Seu momento de cuidado ↗</a></header>
    <section class="mx-auto grid max-w-6xl items-center gap-10 px-6 pb-12 pt-5 md:grid-cols-2 md:gap-16 md:pb-20 md:pt-10"><div><p class="text-[11px] uppercase tracking-[0.22em] text-[#a56b77]">Nail studio · beleza com calma</p><h1 class="mt-6 font-['Playfair_Display'] text-5xl leading-[1.1] tracking-tight sm:text-6xl lg:text-[78px]">Um momento<br>seu.<br><span class="italic text-[#af677d]">Até a ponta<br>dos dedos.</span></h1><p class="mt-7 max-w-sm text-base leading-7 text-[#8b6b71]">Cores que combinam com você. Cuidado que respeita seu ritmo. Encontre um jeito mais leve de se sentir bem.</p><a href="#cuidados" class="mt-8 inline-flex items-center gap-8 rounded-full bg-[#73384a] px-7 py-4 text-sm text-white hover:bg-[#542537]">Encontre seu cuidado <span aria-hidden="true">↗</span></a><p class="mt-5 text-xs text-[#a5838a]">Um estúdio. Muitas formas de expressar você.</p></div><div class="relative pb-8"><img src="/images/campaign/nails-hero.jpg" alt="Mãos com manicure e acabamento delicado" width="900" height="1100" fetchpriority="high" class="aspect-[4/5] w-full rounded-t-[48%] object-cover"><div class="absolute -bottom-1 left-0 max-w-[260px] bg-[#f0dfe1] p-6 md:-left-7"><span class="text-2xl" aria-hidden="true">✳</span><p class="mt-2 font-['Playfair_Display'] text-xl italic leading-snug">Os pequenos cuidados<br>fazem parte de quem somos.</p></div></div></section>
    <section id="cuidados" class="bg-[#f4e8e8] px-6 py-16 md:py-24"><div class="mx-auto grid max-w-6xl gap-12 md:grid-cols-2"><div><p class="text-[11px] uppercase tracking-[0.2em] text-[#a56b77]">O que suas mãos pedem hoje?</p><h2 class="mt-4 font-['Playfair_Display'] text-4xl md:text-5xl">Cuidados para<br><span class="italic">cada versão sua.</span></h2><div class="mt-8 space-y-0" role="group" aria-label="Escolha um serviço"><button v-for="(service, index) in services" :key="service.name" :aria-pressed="selected === index" class="flex w-full items-center justify-between border-b border-[#d9bcc3] py-5 text-left text-base transition-colors" :class="selected === index ? 'font-semibold text-[#73384a]' : 'text-[#997b81]'" @click="selected = index"><span><span class="mr-4 text-xs">0{{ index + 1 }}</span>{{ service.name }}</span><span aria-hidden="true">{{ selected === index ? '↗' : '+' }}</span></button></div></div><div class="flex flex-col justify-center bg-[#fffaf7] p-8 md:p-12" aria-live="polite"><p class="text-xs uppercase tracking-widest text-[#a56b77]">{{ services[selected]?.tag }}</p><h3 class="mt-5 font-['Playfair_Display'] text-3xl">{{ services[selected]?.name }}</h3><p class="mt-5 text-base leading-8 text-[#8b6b71]">{{ services[selected]?.detail }}</p><a href="#conversa" class="mt-8 self-start border-b border-[#73384a] pb-2 text-sm">Gostei desse cuidado ↗</a><p class="mt-8 text-xs leading-6 text-[#a5838a]">A escolha do serviço é ilustrativa nesta demonstração.</p></div></div></section>
    <section id="inspiracao" class="mx-auto max-w-6xl px-6 py-16 md:py-24"><div class="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 class="font-['Playfair_Display'] text-4xl md:text-5xl">Pequenos detalhes.<br><span class="italic">Muitas possibilidades.</span></h2><p class="max-w-xs text-base leading-7 text-[#8b6b71]">Uma galeria de inspiração para escolher seu próximo visual. Toque nas imagens para ver de perto.</p></div><Gallery :images="gallery" /><p class="mt-4 text-xs text-[#a5838a]">Fotografias de referência para este projeto demonstrativo.</p></section>
    <NailsEditorial />
    <section id="duvidas" class="border-y border-[#ead7da] px-6 py-14"><div class="mx-auto grid max-w-6xl gap-10 md:grid-cols-2"><div><p class="text-xs uppercase tracking-widest text-[#a56b77]">Antes da sua visita</p><h2 class="mt-4 font-['Playfair_Display'] text-3xl">Cuidar também é<br>tirar suas dúvidas.</h2></div><div class="space-y-2"><details class="border-b border-[#ead7da] py-4"><summary class="cursor-pointer text-sm">Posso escolher a cor durante o atendimento?</summary><p class="mt-3 text-base leading-7 text-[#8b6b71]">Sim. A proposta do estúdio é ajudar você a encontrar a cor e o acabamento que combinam com seu estilo.</p></details><details class="border-b border-[#ead7da] py-4"><summary class="cursor-pointer text-sm">Como funciona o agendamento neste exemplo?</summary><p class="mt-3 text-base leading-7 text-[#8b6b71]">Esta página demonstra como um estúdio pode apresentar seus serviços. Não há uma agenda real. A conversa abaixo é com a Avyro, sobre criar um site.</p></details></div></div></section>
    <section id="conversa" class="px-6 py-16 text-center"><p class="text-xs uppercase tracking-[0.2em] text-[#a56b77]">Seu estúdio pode ter um espaço assim</p><h2 class="mt-4 font-['Playfair_Display'] text-4xl italic">Vamos dar forma à sua marca?</h2><a :href="contact" target="_blank" rel="noopener noreferrer" class="mt-7 inline-flex rounded-full bg-[#73384a] px-8 py-4 text-sm text-white hover:bg-[#542537]">Quero um site como este ↗</a><p class="mt-4 text-xs text-[#a5838a]">Você vai conversar com a Avyro. Nenhum horário será reservado.</p></section>
    <footer class="flex flex-wrap justify-between gap-4 border-t border-[#ead7da] px-6 py-6 text-xs text-[#a5838a]"><span>BellaNails · Projeto demonstrativo</span><NuxtLink to="/#portfolio" class="hover:underline">Design & desenvolvimento Avyro ↗</NuxtLink></footer>
  </div>
</template>
