<script setup lang="ts">
import WoodBrief from '~/components/campaign/WoodBrief.vue'
import DemoContact from '~/components/campaign/DemoContact.vue'
import { woodRooms, woodFinishes } from '~/constants/sectorDemos'
definePageMeta({ layout: 'demonstracao' })
useDemoSeo('Veio — marcenaria para habitar', 'Modelo de site para móveis planejados com exploração de ambientes e seleção de acabamentos.')
const { index: roomIndex, current: room, choose: chooseRoom } = useDemoChoice(woodRooms)
const { index: finishIndex, current: finish, choose: chooseFinish } = useDemoChoice(woodFinishes)
</script>
<template>
  <div class="bg-[#ece7df] text-[#463d32]">
    <header class="flex flex-wrap items-center justify-between gap-5 px-6 py-7 md:px-12"><NuxtLink to="/exemplos/marcenaria" class="font-['Playfair_Display'] text-4xl tracking-tight">veio<span class="ml-4 font-body text-xs uppercase tracking-[0.2em]">marcenaria</span></NuxtLink><nav aria-label="Veio" class="flex gap-7 text-sm"><a href="#ambientes">Ambientes</a><a href="#materiais">Matéria</a><a href="#processo">Do desenho à casa</a></nav></header>
    <section class="relative isolate min-h-[620px] bg-[#463d32] text-white"><img src="/images/campaign/wood-kitchen.jpg" alt="Cozinha com armários em madeira e integração com a paisagem" width="1600" height="1000" fetchpriority="high" class="absolute inset-0 -z-20 h-full w-full object-cover"><div class="absolute inset-0 -z-10 bg-black/40" /><div class="mx-auto flex min-h-[620px] max-w-7xl flex-col justify-end px-6 pb-14 pt-24 md:px-12"><p class="text-sm uppercase tracking-[0.25em]">Matéria. Medida. Memória.</p><h1 class="mt-5 font-['Playfair_Display'] text-6xl leading-[1.05] md:text-8xl">Feito para<br><span class="italic">pertencer.</span></h1><div class="mt-8 flex flex-col justify-between gap-6 md:flex-row md:items-end"><p class="max-w-md text-lg leading-8 text-white/85">Móveis que encontram o seu lugar na casa.<br>E na vida de quem mora nela.</p><a href="#ambientes" class="border-b border-white pb-3 text-base">Descubra os ambientes ↓</a></div></div></section>
    <section id="ambientes" class="px-6 py-20 md:px-12"><div class="mx-auto max-w-7xl"><div class="flex flex-col justify-between gap-7 md:flex-row md:items-end"><h2 class="font-['Playfair_Display'] text-4xl md:text-5xl">O desenho começa<br>na sua rotina.</h2><div class="flex flex-wrap gap-5" role="group" aria-label="Ambientes de marcenaria"><button v-for="(item, i) in woodRooms" :key="item.name" :aria-pressed="roomIndex === i" class="border-b-2 pb-3 text-sm" :class="roomIndex === i ? 'border-[#463d32] font-semibold' : 'border-transparent text-[#887e70] hover:border-[#887e70]'" @click="chooseRoom(i)">{{ item.name }}</button></div></div><div class="mt-10 grid gap-8 lg:grid-cols-[1.7fr_0.7fr]"><img :src="room.image" :alt="`Referência ilustrativa de ${room.name}`" width="1200" height="900" loading="lazy" class="aspect-[1.35] w-full object-cover"><div class="flex flex-col justify-center py-5" aria-live="polite"><p class="text-sm uppercase tracking-widest text-[#948571]">Coleção de ambientes / 0{{ roomIndex + 1 }}</p><h3 class="mt-6 font-['Playfair_Display'] text-4xl">{{ room.title }}</h3><p class="mt-6 text-base leading-8 text-[#807464]">{{ room.detail }}</p><ul class="mt-8 space-y-3 border-t border-[#ccc3b6] pt-6 text-sm"><li v-for="feature in room.features" :key="feature">— {{ feature }}</li></ul></div></div></div></section>
    <section id="materiais" class="bg-[#463d32] px-6 py-20 text-[#ece7df] md:px-12"><div class="mx-auto grid max-w-6xl gap-12 md:grid-cols-2"><div><p class="text-sm uppercase tracking-[0.18em] text-[#bfb09c]">Um repertório de possibilidades</p><h2 class="mt-6 font-['Playfair_Display'] text-4xl leading-tight md:text-5xl">A matéria também<br>conta a sua história.</h2><p class="mt-6 max-w-md text-base leading-8 text-[#bfb09c]">Explore uma paleta de referência. Tom, toque e composição são escolhidos junto com o desenho do móvel.</p><div class="mt-9 flex flex-wrap gap-4" role="group" aria-label="Paleta de acabamentos"><button v-for="(item, i) in woodFinishes" :key="item.name" :aria-label="item.name" :aria-pressed="finishIndex === i" class="h-14 w-14 rounded-full border-4 transition-transform hover:scale-105" :class="finishIndex === i ? 'border-white' : 'border-transparent'" :style="{ backgroundColor: item.color }" @click="chooseFinish(i)" /></div></div><div class="flex flex-col justify-center border border-[#766959] p-8 md:p-12" aria-live="polite"><div class="mb-7 h-3 w-24" :style="{ backgroundColor: finish.color }" /><p class="text-sm text-[#bfb09c]">ACABAMENTO SELECIONADO</p><h3 class="mt-5 font-['Playfair_Display'] text-4xl">{{ finish.name }}</h3><p class="mt-6 text-base leading-8 text-[#bfb09c]">{{ finish.text }}</p><p class="mt-7 text-sm leading-6 text-[#bfb09c]">A paleta é ilustrativa e não altera a fotografia do ambiente. Cores podem variar entre telas e amostras.</p></div></div></section>
    <section id="processo" class="mx-auto max-w-7xl px-6 py-20 md:px-12"><p class="text-sm uppercase tracking-widest text-[#948571]">Do primeiro traço ao último detalhe</p><ol class="mt-10 grid gap-8 md:grid-cols-4"><li v-for="(step, i) in [{ title: 'Escutar', text: 'Rotina, objetos e desejos orientam o começo.' }, { title: 'Desenhar', text: 'Medidas e proporções dão forma às ideias.' }, { title: 'Escolher', text: 'Materiais e ferragens completam o projeto.' }, { title: 'Instalar', text: 'O desenho encontra o ambiente e seus detalhes.' }]" :key="step.title" class="border-t border-[#ccc3b6] pt-5"><p class="text-sm text-[#948571]">0{{ i + 1 }}</p><h2 class="mt-5 font-['Playfair_Display'] text-3xl">{{ step.title }}</h2><p class="mt-4 text-base leading-7 text-[#807464]">{{ step.text }}</p></li></ol></section>
    <WoodBrief />
    <DemoContact name="Veio Marcenaria" :subject="`um site para marcenaria como o Veio, com ambientes e acabamentos (${room.name}, ${finish.name})`" title="Seu trabalho merece ser visto nos detalhes." />
  </div>
</template>
