<script setup lang="ts">
import DentalComfort from '~/components/campaign/DentalComfort.vue'
import DemoContact from '~/components/campaign/DemoContact.vue'
import { dentalCare } from '~/constants/sectorDemos'
definePageMeta({ layout: 'demonstracao' })
useDemoSeo('Serena — odontologia com escuta', 'Modelo de site odontológico com apresentação de cuidados, visita à clínica e jornada de avaliação.')
const { index, current, choose } = useDemoChoice(dentalCare)
</script>
<template>
  <div class="bg-[#faf8f3] text-[#344c43]">
    <header class="flex flex-wrap items-center justify-between gap-6 border-b border-[#dedfd5] px-6 py-7 md:px-12"><NuxtLink to="/exemplos/odontologia" class="font-['Playfair_Display'] text-4xl">serena<span class="ml-3 font-body text-xs uppercase tracking-[0.2em]">odontologia</span></NuxtLink><nav aria-label="Serena" class="flex gap-6 text-sm"><a href="#cuidados">Cuidados</a><a href="#clinica">A clínica</a><a href="#primeira-visita">Primeira visita ↗</a></nav></header>
    <section class="mx-auto max-w-7xl px-6 pb-16 pt-14 md:px-12"><div class="grid gap-10 md:grid-cols-[1.2fr_0.8fr] md:items-end"><h1 class="font-['Playfair_Display'] text-5xl leading-[1.12] tracking-tight md:text-7xl">Antes do sorriso,<br><span class="italic text-[#819383]">a pessoa.</span></h1><div><p class="text-lg leading-8 text-[#758178]">Tempo para ouvir. Clareza para explicar. Um cuidado que começa na forma de receber você.</p><a href="#cuidados" class="mt-7 inline-flex items-center gap-10 border-b border-[#344c43] pb-3 text-sm font-semibold">Conheça nossos cuidados ↓</a></div></div><div class="mt-12 grid gap-4 md:grid-cols-[1.4fr_0.6fr]"><img src="/images/campaign/dental-care.jpg" alt="Conversa entre profissional e paciente em ambiente odontológico, foto ilustrativa" width="1400" height="900" fetchpriority="high" class="aspect-[1.4] w-full rounded-t-[100px] object-cover md:rounded-tl-[120px] md:rounded-tr-none"><div class="flex flex-col justify-between rounded-br-[100px] bg-[#e5e9df] p-8 md:p-10"><span class="font-['Playfair_Display'] text-6xl text-[#899b88]" aria-hidden="true">“</span><p class="font-['Playfair_Display'] text-3xl leading-snug">Seu tempo.<br>Suas dúvidas.<br>Seu cuidado.</p><p class="mt-8 text-sm leading-6">Uma experiência pensada para acolher, desde a primeira conversa.</p></div></div></section>
    <section id="cuidados" class="bg-white px-6 py-16 md:px-12 md:py-24"><div class="mx-auto max-w-6xl"><p class="text-sm uppercase tracking-widest text-[#819383]">Cuidado individual, sempre</p><h2 class="mt-4 font-['Playfair_Display'] text-4xl md:text-5xl">O que trouxe você até aqui?</h2><div class="mt-10 grid gap-10 md:grid-cols-[0.7fr_1.3fr]"><div role="group" aria-label="Áreas de cuidado"><button v-for="(item, i) in dentalCare" :key="item.name" :aria-pressed="index === i" class="flex w-full justify-between border-b border-[#dce2da] py-6 text-left text-xl" :class="index === i ? 'font-semibold text-[#344c43]' : 'text-[#7e8b81]'" @click="choose(i)">{{ item.name }}<span aria-hidden="true">{{ index === i ? '−' : '+' }}</span></button></div><article class="rounded-3xl bg-[#f0f3eb] p-8 md:p-12" aria-live="polite"><h3 class="font-['Playfair_Display'] text-3xl leading-snug">{{ current.title }}</h3><p class="mt-6 text-base leading-8 text-[#69796d]">{{ current.text }}</p><ol class="mt-7 space-y-4"><li v-for="(step, i) in current.steps" :key="step" class="flex gap-4 text-base"><span class="text-[#8a9b84]">0{{ i + 1 }}</span>{{ step }}</li></ol><p class="mt-8 border-t border-[#d3ddcf] pt-5 text-sm leading-6 text-[#69796d]">A indicação de qualquer tratamento depende de avaliação individual por um cirurgião-dentista.</p></article></div></div></section>
    <section id="clinica" class="mx-auto grid max-w-6xl gap-12 px-6 py-20 md:grid-cols-2 md:items-center"><img src="/images/campaign/dental.jpg" alt="Estrutura de consultório odontológico, imagem de referência" width="900" height="1100" loading="lazy" class="aspect-[4/5] w-full rounded-t-full object-cover"><div><p class="text-sm uppercase tracking-widest text-[#819383]">Espaço para se sentir à vontade</p><h2 class="mt-6 font-['Playfair_Display'] text-4xl leading-tight md:text-5xl">Uma consulta também<br>é uma conversa.</h2><p class="mt-6 text-base leading-8 text-[#758178]">Perguntar, entender as possibilidades e participar das decisões. A experiência de cuidado dá espaço para cada uma dessas etapas.</p><div class="mt-8 border-y border-[#dce2da] py-6 text-base leading-8">Escuta atenta · Explicações claras · Planejamento individual</div><p class="mt-6 text-sm text-[#758178]">Serena é uma clínica fictícia. Este exemplo não oferece consultas ou tratamentos reais.</p></div></section>
    <section id="primeira-visita" class="bg-[#e5e9df] px-6 py-16 md:px-12"><div class="mx-auto max-w-6xl"><h2 class="font-['Playfair_Display'] text-4xl">Sua primeira visita, com calma.</h2><div class="mt-10 grid gap-8 md:grid-cols-3"><article v-for="(step, i) in [{ title: 'Conte sua história', text: 'O motivo da visita e suas expectativas abrem a conversa.' }, { title: 'Entenda a avaliação', text: 'O profissional explica o que está sendo observado.' }, { title: 'Converse sobre o plano', text: 'As possibilidades são discutidas antes das decisões.' }]" :key="step.title"><p class="text-sm text-[#819383]">PASSO 0{{ i + 1 }}</p><h3 class="mt-4 text-xl font-semibold">{{ step.title }}</h3><p class="mt-3 text-base leading-7 text-[#69796d]">{{ step.text }}</p></article></div></div></section>
    <DentalComfort />
    <DemoContact name="Serena Odontologia" subject="um site para clínica odontológica como o Serena" title="A experiência da sua clínica pode começar no site." />
  </div>
</template>
