<script setup lang="ts">
import WorkshopHistory from '~/components/campaign/WorkshopHistory.vue'
import { campaignWhatsapp } from '~/utils/campaign'
definePageMeta({ layout: 'demonstracao' })
useDemoSeo('AutoElite — atenção em cada quilômetro', 'Demonstração de site para oficina: revisão, freios, diagnóstico e apresentação do atendimento.')
const services = [
  { name: 'Revisão preventiva', icon: 'fact_check', title: 'Antes de pegar a estrada, um olhar completo.', text: 'Avaliamos os sistemas do veículo, verificamos os itens de desgaste e explicamos quais cuidados precisam de atenção.', includes: ['Inspeção visual', 'Verificação de fluidos', 'Avaliação de componentes'] },
  { name: 'Freios & suspensão', icon: 'tire_repair', title: 'Atenção ao que mantém você no controle.', text: 'Ruídos, vibrações ou mudanças na frenagem? Verificamos os componentes para identificar a origem e orientar o reparo.', includes: ['Pastilhas e discos', 'Componentes da suspensão', 'Identificação de ruídos'] },
  { name: 'Diagnóstico eletrônico', icon: 'monitor_heart', title: 'Entender primeiro. Resolver depois.', text: 'Investigamos os sinais do painel e a leitura dos sistemas eletrônicos para identificar a falha antes de propor uma solução.', includes: ['Leitura de falhas', 'Avaliação dos sistemas', 'Orientação técnica'] },
  { name: 'Óleo & filtros', icon: 'oil_barrel', title: 'Cuidado básico. Diferença no dia a dia.', text: 'Conferimos as especificações do seu veículo e o intervalo de manutenção para orientar a troca de óleo e filtros.', includes: ['Identificação do lubrificante', 'Avaliação dos filtros', 'Orientação de manutenção'] },
]
const selected = ref<number>(0)
</script>
<template>
  <div class="bg-[#f5f5f3] text-[#202522]">
    <header class="bg-[#202522] text-white"><div class="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-5 px-6 py-6"><NuxtLink to="/exemplos/oficina" class="font-heading text-2xl font-extrabold italic tracking-tight">AUTO<span class="text-[#f4b544]">ELITE</span><span class="ml-3 hidden text-[10px] font-normal not-italic tracking-[0.15em] text-stone-400 sm:inline">CENTRO AUTOMOTIVO</span></NuxtLink><nav class="flex gap-6 text-xs" aria-label="AutoElite"><a href="#servicos" class="hover:text-[#f4b544]">Serviços</a><a href="#atendimento" class="hover:text-[#f4b544]">Como atendemos</a><a href="#contato" class="text-[#f4b544]">Fale com a gente ↗</a></nav></div></header>
    <section class="bg-[#202522] text-white"><div class="mx-auto grid max-w-6xl gap-10 px-6 pb-16 pt-10 md:grid-cols-2 md:items-center md:py-16"><div><p class="text-[11px] font-semibold uppercase tracking-[0.2em] text-[#f4b544]">Cuidado que acompanha seu caminho</p><h1 class="mt-6 font-heading text-5xl font-bold leading-[1.06] tracking-[-0.045em] md:text-6xl">Seu carro em dia.<br><span class="text-[#f4b544]">Você segue<br>tranquilo.</span></h1><p class="mt-6 max-w-md text-base leading-7 text-stone-400">Da revisão ao diagnóstico. Um atendimento que explica, orienta e ajuda você a cuidar melhor do seu veículo.</p><a href="#servicos" class="mt-8 inline-flex items-center gap-7 bg-[#f4b544] px-6 py-4 text-sm font-bold text-[#202522] hover:bg-[#ffd179]">De qual serviço você precisa? <span aria-hidden="true">↓</span></a></div><div><img src="/images/campaign/workshop.jpg" alt="Diagnóstico e manutenção de um veículo em oficina" width="1000" height="1000" fetchpriority="high" class="aspect-square w-full object-cover"><div class="flex items-center justify-between border-b border-stone-600 py-4 text-[11px] uppercase tracking-widest text-stone-400"><span>Revisão · Diagnóstico · Manutenção</span><span class="text-[#f4b544]" aria-hidden="true">↗</span></div></div></div></section>
    <section id="servicos" class="mx-auto max-w-6xl px-6 py-16 md:py-24"><div class="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p class="text-xs font-semibold uppercase tracking-[0.17em] text-[#987024]">Serviço certo, conversa clara</p><h2 class="mt-4 font-heading text-3xl font-bold tracking-tight md:text-4xl">Como podemos ajudar seu carro?</h2></div><p class="max-w-xs text-base leading-7 text-stone-500">Escolha uma área para conhecer a proposta de atendimento.</p></div><div class="mt-10 grid gap-0 border border-stone-300 md:grid-cols-[1fr_1.5fr]"><div role="group" aria-label="Serviços automotivos"><button v-for="(item, i) in services" :key="item.name" :aria-pressed="selected === i" class="flex w-full items-center gap-4 border-b border-stone-300 px-6 py-6 text-left text-sm font-semibold last:border-b-0" :class="selected === i ? 'bg-[#202522] text-[#f4b544]' : 'bg-white text-stone-600 hover:bg-stone-100'" @click="selected = i"><span class="material-symbols-outlined" aria-hidden="true">{{ item.icon }}</span>{{ item.name }}<span class="ml-auto" aria-hidden="true">→</span></button></div><div class="bg-white p-8 md:p-10" aria-live="polite"><p class="text-xs uppercase tracking-[0.14em] text-[#987024]">{{ services[selected]?.name }}</p><h3 class="mt-4 font-heading text-2xl font-bold leading-snug">{{ services[selected]?.title }}</h3><p class="mt-4 text-base leading-7 text-stone-500">{{ services[selected]?.text }}</p><ul class="mt-6 space-y-3 text-sm text-stone-600"><li v-for="item in services[selected]?.includes" :key="item"><span class="mr-3 text-[#a57520]" aria-hidden="true">✓</span>{{ item }}</li></ul><a href="#contato" class="mt-8 inline-block border-b border-stone-800 pb-2 text-sm font-bold">Conhecer esta solução de site ↗</a></div></div></section>
    <section id="atendimento" class="border-y border-stone-300 bg-[#eeefeb] px-6 py-16"><div class="mx-auto max-w-6xl"><p class="text-xs font-semibold uppercase tracking-widest text-[#987024]">Você acompanha cada etapa</p><h2 class="mt-4 font-heading text-3xl font-bold tracking-tight">Bom atendimento também é transparência.</h2><div class="mt-10 grid gap-8 md:grid-cols-3"><article v-for="(step, i) in [{ title: 'Você conta o que acontece.', text: 'O atendimento começa entendendo o veículo e o que você percebe no dia a dia.' }, { title: 'A avaliação vira orientação.', text: 'O cliente recebe uma explicação do diagnóstico e dos serviços propostos.' }, { title: 'O próximo passo é combinado.', text: 'Escopo e condições são conversados antes da execução do serviço.' }]" :key="step.title"><p class="font-heading text-4xl font-bold text-stone-300">0{{ i + 1 }}</p><h3 class="mt-5 text-lg font-bold">{{ step.title }}</h3><p class="mt-3 text-base leading-7 text-stone-500">{{ step.text }}</p></article></div></div></section>
    <section class="mx-auto grid max-w-6xl gap-10 px-6 py-16 md:grid-cols-2"><h2 class="font-heading text-3xl font-bold tracking-tight">Antes de falar<br>com a oficina.</h2><div><details class="border-b border-stone-300 py-4"><summary class="cursor-pointer text-sm font-semibold">O orçamento pode ser explicado pelo site?</summary><p class="mt-3 text-base leading-7 text-stone-500">O site pode organizar os serviços e facilitar o primeiro contato. O diagnóstico e o orçamento do veículo dependem da avaliação da oficina.</p></details><details class="border-b border-stone-300 py-4"><summary class="cursor-pointer text-sm font-semibold">Este site recebe agendamentos reais?</summary><p class="mt-3 text-base leading-7 text-stone-500">Não. AutoElite é um exemplo da Avyro. Você pode explorar os serviços e conversar sobre um site para sua própria oficina.</p></details></div></section>
    <WorkshopHistory />
    <section id="contato" class="bg-[#f4b544] px-6 py-14"><div class="mx-auto flex max-w-6xl flex-col justify-between gap-7 md:flex-row md:items-center"><div><p class="text-xs font-semibold uppercase tracking-widest">Sua oficina pode ser o próximo projeto</p><h2 class="mt-3 font-heading text-3xl font-bold tracking-tight">Leve esse atendimento para o seu site.</h2></div><a :href="campaignWhatsapp(`um site para oficina como o AutoElite, com apresentação de ${services[selected]?.name}`)" target="_blank" rel="noopener noreferrer" class="inline-flex shrink-0 items-center justify-center bg-[#202522] px-7 py-4 text-sm font-bold text-white hover:bg-stone-700">Conversar com a Avyro ↗</a></div></section>
    <footer class="flex flex-wrap justify-between gap-4 bg-[#202522] px-6 py-6 text-xs text-stone-400"><span>AutoElite · Empresa demonstrativa</span><NuxtLink to="/#portfolio">Site criado pela Avyro ↗</NuxtLink></footer>
  </div>
</template>
