<script setup lang="ts">
import { serviceLandings } from '~/constants/services'
import { campaignWhatsapp } from '~/utils/campaign'
definePageMeta({ layout: 'marketing', key: route => route.path, validate: route => serviceLandings.some(item => item.slug === route.params.segmento) })
const route = useRoute()
const service = serviceLandings.find(item => item.slug === route.params.segmento)
if (!service) throw createError({ statusCode: 404, statusMessage: 'Segmento não encontrado' })
useMarketingSeo(service.title, service.description, `/criacao-de-sites/${service.slug}`)
const contact = campaignWhatsapp(`criação de site para ${service.audience.toLowerCase()}, com proposta personalizada`)
const origin = String(useRuntimeConfig().public.siteUrl).replace(/\/$/, '')
useHead({ script: [{ type: 'application/ld+json', innerHTML: JSON.stringify({ '@context': 'https://schema.org', '@type': 'Service', name: service.title, description: service.description, url: `${origin}/criacao-de-sites/${service.slug}`, provider: { '@type': 'Organization', name: 'Avyro', url: origin } }) }] })
</script>
<template>
  <div v-if="service">
    <section class="mx-auto grid max-w-[1240px] gap-10 px-5 py-12 md:px-8 lg:grid-cols-[1.1fr_1fr] lg:items-center lg:py-20"><div><NuxtLink to="/criacao-de-sites" class="text-sm text-slate-500">← Sites por segmento</NuxtLink><p class="mt-8 text-xs font-semibold uppercase tracking-widest text-[#255bef]">Avyro / {{ service.title }}</p><h1 class="mt-5 font-heading text-4xl font-semibold leading-tight tracking-tight md:text-5xl">{{ service.title }}</h1><p class="mt-6 text-lg leading-8 text-slate-600">{{ service.intro }}</p><a :href="contact" target="_blank" rel="noopener noreferrer" class="mt-8 inline-flex min-h-12 items-center rounded-lg bg-[#255bef] px-6 py-4 text-sm font-semibold text-white">Conversar sobre meu projeto ↗</a><p class="mt-4 text-xs leading-6 text-slate-500">Proposta conforme seu negócio. Manutenção mensal opcional.</p></div><figure><img :src="`/images/campaign/${service.image}`" :alt="`Referência visual do modelo de site para ${service.audience.toLowerCase()}`" width="1000" height="850" fetchpriority="high" class="aspect-[5/4] w-full rounded-2xl object-cover"><figcaption class="mt-4 text-xs text-slate-500">Referência do modelo demonstrativo · conteúdo adaptado à sua marca no projeto.</figcaption></figure></section>
    <section class="border-y border-slate-200 bg-slate-50 px-5 py-16 md:px-8"><div class="mx-auto max-w-[1176px]"><h2 class="max-w-3xl font-heading text-3xl font-semibold tracking-tight md:text-4xl">{{ service.heading }}</h2><div class="mt-9 grid gap-8 md:grid-cols-3"><article v-for="(need, i) in service.needs" :key="need.title" class="border-t border-slate-300 pt-5"><p class="text-sm text-[#255bef]">0{{ i + 1 }}</p><h3 class="mt-4 text-xl font-semibold">{{ need.title }}</h3><p class="mt-4 text-base leading-7 text-slate-600">{{ need.text }}</p></article></div></div></section>
    <section class="mx-auto grid max-w-[1240px] gap-10 px-5 py-16 md:grid-cols-2 md:px-8"><div><p class="text-xs uppercase tracking-widest text-[#255bef]">Veja as possibilidades</p><h2 class="mt-4 font-heading text-3xl font-semibold">Explore um exemplo para {{ service.audience.toLowerCase() }}.</h2><p class="mt-5 text-base leading-8 text-slate-600">O exemplo mostra uma direção de design e funcionalidades. Seu site terá conteúdo, identidade e recursos definidos para a sua empresa.</p><NuxtLink :to="`/exemplos/${service.demo}`" class="mt-6 inline-flex min-h-12 items-center border-b border-[#255bef] text-sm font-semibold text-[#255bef]">Abrir demonstração completa ↗</NuxtLink><NuxtLink v-if="service.slug === 'floriculturas'" to="/exemplos/floricultura-atelie" class="mt-3 block py-3 text-sm text-[#255bef]">Ver também o modelo de ateliê floral ↗</NuxtLink></div><div class="rounded-xl border border-slate-200 p-6 sm:p-8"><h2 class="text-2xl font-semibold">Como seu projeto ganha forma</h2><ol class="mt-6 space-y-5 text-sm leading-7 text-slate-600"><li><strong class="text-slate-900">1. Entendemos seu negócio.</strong> Público, serviços, conteúdo disponível e objetivos.</li><li><strong class="text-slate-900">2. Definimos uma proposta.</strong> Páginas, funcionalidades, responsabilidades e prazo.</li><li><strong class="text-slate-900">3. Criamos e revisamos.</strong> Design, implementação e ajustes antes da entrega.</li><li><strong class="text-slate-900">4. Planejamos a continuidade.</strong> Manutenção opcional e orientação sobre atualizações.</li></ol></div></section>
    <section class="mx-auto max-w-4xl px-5 pb-16"><h2 class="text-3xl font-semibold">Antes da primeira conversa</h2><details class="mt-7 border-y border-slate-200 py-5"><summary class="min-h-11 cursor-pointer text-lg font-medium">{{ service.question }}</summary><p class="mt-4 text-base leading-8 text-slate-600">{{ service.answer }}</p></details><details class="border-b border-slate-200 py-5"><summary class="min-h-11 cursor-pointer text-lg font-medium">Como são definidos os valores?</summary><p class="mt-4 text-base leading-8 text-slate-600">A proposta considera páginas, conteúdo, funcionalidades e integrações. Conversamos sobre sua necessidade antes de definir o investimento, sem pacotes iguais para negócios diferentes.</p></details><details class="border-b border-slate-200 py-5"><summary class="min-h-11 cursor-pointer text-lg font-medium">Posso contratar manutenção e painel?</summary><p class="mt-4 text-base leading-8 text-slate-600">Sim. A manutenção mensal é opcional e tem atividades combinadas. Um painel pode ser incluído quando fizer sentido atualizar conteúdo por conta própria, com recursos definidos no escopo.</p></details></section>
    <section class="bg-[#101c35] px-5 py-14 text-white"><div class="mx-auto max-w-[1176px]"><h2 class="text-3xl font-semibold">Vamos conversar sobre o seu site?</h2><p class="mt-4 max-w-xl text-base leading-7 text-slate-300">Conte o que sua empresa faz e o que precisa melhorar na presença digital. A Avyro prepara uma proposta a partir dessa conversa.</p><a :href="contact" target="_blank" rel="noopener noreferrer" class="mt-7 inline-flex min-h-12 items-center rounded-lg bg-white px-6 py-4 text-sm font-semibold text-[#101c35]">Falar com a Avyro pelo WhatsApp ↗</a></div></section>
  </div>
</template>
